// Ingredient knowledge base (starter set).
// Ratings follow public regulatory and safety sources, but nobody with cosmetic-science training
// has reviewed them yet. RULE: when sources disagree, the stricter regulator wins (EU first, then
// Korea MFDS, then US/international sources). "bad" is reserved for substances an EU or Korean rule bans,
// restricts or requires to be named as an allergen (or an SCCS concern). Irritation or pore-clogging alone is at most "mid". `src` points to the source DATABASES, not to the exact entry, so a reader can
// look the ingredient up there. Notes are general information, not medical advice.
//
// Each group: [level, names, note, detail, risks, helps, src]
//   level: "good" | "mid" | "bad"
//   risks: allergy, irritation, hormone, cancer, restricted, comedogenic, sun, pregnancy, drying
//   helps: acne, redness, dryness, pigmentation, lines
(function () {
  var SOURCES = {
    // rank: lower = stricter and more trusted. EU first, then Korea, then the rest.
    // Policy: only regulators, public-health agencies, medical societies and non-profits.
    // NOT used: industry-funded panels (CIR is paid for by the cosmetics trade association),
    // fragrance-industry bodies (IFRA, RIFM) and brand-paid certification programs.
    EUREG: { name: "EU Cosmetics Regulation", url: "https://eur-lex.europa.eu/eli/reg/2009/1223/oj", rank: 0 },
    SCCS: { name: "EU SCCS opinions", url: "https://health.ec.europa.eu/scientific-committees/scientific-committee-consumer-safety-sccs_en", rank: 0 },
    COSING: { name: "EU CosIng database", url: "https://single-market-economy.ec.europa.eu/sectors/cosmetics/cosmetic-ingredient-database_en", rank: 0 },
    ECHA: { name: "ECHA hazard classifications", url: "https://echa.europa.eu/information-on-chemicals/cl-inventory-database", rank: 0 },
    MFDS: { name: "Korea MFDS", url: "https://www.mfds.go.kr/eng/index.do", rank: 1 },
    MHLW: { name: "Japan MHLW cosmetic standards", url: "https://www.mhlw.go.jp/file/06-Seisakujouhou-11120000-Iyakushokuhinkyoku/keshouhin-standard.pdf", rank: 1 },
    NMPA: { name: "China NMPA prohibited list", url: "https://www.samr.gov.cn/xw/mtjj/art/2023/art_4bed22b4d6f647f4994fc2356ed34538.html", rank: 1 },
    NIHS: { name: "Japan NIHS report (wheat protein)", url: "https://www.nihs.go.jp/kanren/shokuhin/20131116-dnfi.pdf", rank: 1 },
    FSC: { name: "Japan Food Safety Commission (carmine)", url: "https://www.fsc.go.jp/sonota/cochineal.pdf", rank: 1 },
    FUJITA: { name: "Fujita Health University (Japan)", url: "https://www.fujita-hu.ac.jp/news/dubv6r0000001rc3.html", rank: 2 },
    PSJ: { name: "Pharmaceutical Society of Japan (carmine)", url: "https://www.jstage.jst.go.jp/article/faruawpsj/50/6/50_522/_article/-char/ja/", rank: 2 },
    CPU: { name: "China Pharmaceutical University (2025)", url: "https://www.cpu.edu.cn/_t858/5d/67/c11540a220519/page.htm", rank: 2 },
    MFDSF: { name: "Korea MFDS (fragrance allergens)", url: "https://www.mfds.go.kr/eng/brd/m_75/view.do?seq=13", rank: 1 },
    IARC: { name: "IARC (WHO)", url: "https://monographs.iarc.who.int/list-of-classifications", rank: 2 },
    ACDS: { name: "American Contact Dermatitis Society", url: "https://www.contactderm.org/", rank: 2 },
    MTB: { name: "MotherToBaby (pregnancy)", url: "https://mothertobaby.org/fact-sheets/", rank: 2 }
  };

  // "allergy" here means the substance CAN CAUSE allergy in some people (they may become allergic after repeated contact).
  // Allergens that only matter to people who are already allergic (nuts, wheat, bee products...) are in profile.js.
  var RISK_LABEL = {
    allergy: "Can cause allergy",
    irritation: "Can irritate",
    hormone: "Hormone or reproductive",
    cancer: "Cancer concern",
    restricted: "Regulated",
    comedogenic: "May clog pores",
    sun: "Sun sensitivity",
    pregnancy: "Ask a doctor if pregnant",
    drying: "Drying"
  };
  var RISK_ICON = {
    allergy: "alert", irritation: "flame", hormone: "activity", cancer: "circle-alert", restricted: "scale",
    comedogenic: "circle-dot", sun: "sun", pregnancy: "info", drying: "droplet"
  };

  var RAW = [
    // good
    ["good", ["water", "aqua", "eau", "aqua/water", "aqua/water/eau", "water/aqua", "water/aqua/eau", "water/eau", "purified water", "aqua (water)"], "Water", "The base of most formulas. No known concerns.", [], [], ["COSING"]],
    ["good", ["glycerin", "glycerine"], "Humectant, pulls water into the skin", "One of the most widely used moisturizing ingredients. Reviewed as safe in cosmetics and rarely irritating.", [], ["dryness"], ["COSING"]],
    ["good", ["hyaluronic acid", "sodium hyaluronate", "hydrolyzed hyaluronic acid", "sodium acetylated hyaluronate", "hydrolyzed sodium hyaluronate", "sodium hyaluronate crosspolymer"], "Humectant, plumps and hydrates", "Holds water at the skin's surface. Well tolerated by most skin types.", [], ["dryness", "lines"], ["COSING"]],
    ["good", ["ceramide np", "ceramide ap", "ceramide eop", "ceramide ng", "ceramide ns"], "Supports the skin barrier", "Skin-identical lipids that help keep moisture in. Useful for dry or easily irritated skin.", [], ["dryness", "redness"], ["COSING"]],
    ["good", ["cholesterol"], "Skin-identical lipid, supports the barrier", "Works together with ceramides to rebuild the skin barrier.", [], ["dryness"], ["COSING"]],
    ["good", ["panthenol", "pro-vitamin b5", "provitamin b5"], "Soothing and hydrating", "A vitamin B5 derivative that hydrates and calms skin. Well tolerated.", [], ["dryness", "redness"], ["COSING"]],
    ["good", ["niacinamide"], "Supports the barrier and evens tone", "Vitamin B3. Often used for uneven tone and oily skin. A few people feel tingling at high strengths. A 2025 lab-model study from China Pharmaceutical University found skin bacteria can convert it into nicotinic acid (niacin); what that means on real skin is not established.", [], ["pigmentation", "acne", "redness"], ["COSING", "CPU"]],
    ["good", ["squalane"], "Lightweight emollient", "Softens skin without a greasy feel. Usually well tolerated.", [], ["dryness"], ["COSING"]],
    ["good", ["tocopherol", "vitamin e", "tocopheryl acetate", "tocopheryl linoleate", "vitamin e acetate"], "Antioxidant", "Vitamin E. Protects the formula and the skin from oxidation. Contact allergy is rare.", [], ["lines"], ["COSING"]],
    ["good", ["allantoin"], "Soothing", "Calms and softens skin. Well tolerated.", [], ["redness", "dryness"], ["COSING"]],
    ["good", ["centella asiatica extract", "centella asiatica leaf extract", "madecassoside"], "Soothing", "Plant extract used in \"cica\" products to calm irritated skin. Contact allergy has been reported but is uncommon.", [], ["redness"], ["COSING"]],
    ["good", ["aloe barbadensis leaf juice", "aloe barbadensis leaf extract", "aloe barbadensis leaf juice powder", "aloe barbadensis leaf powder"], "Soothing and hydrating", "Gel from the aloe plant that hydrates and calms skin.", [], ["redness", "dryness"], ["COSING"]],
    ["good", ["butyrospermum parkii butter", "butyrospermum parkii (shea) butter"], "Rich emollient", "A rich butter that softens dry skin. Can feel heavy on oily skin.", [], ["dryness"], ["COSING"]],
    ["good", ["cetearyl alcohol", "cetyl alcohol", "stearyl alcohol"], "Fatty alcohol, softens skin (not drying)", "Waxy ingredients that thicken creams. Different from drying alcohols such as ethanol.", [], [], ["COSING"]],
    ["good", ["zinc oxide"], "Mineral UV filter, gentle", "Sits on the skin and reflects UV light. A good choice for sensitive skin. Avoid sprays or powders you could inhale.", [], [], ["SCCS", "COSING"]],
    ["good", ["titanium dioxide", "ci 77891"], "Mineral UV filter or pigment", "Used as a sunscreen filter and white pigment. EU scientists advise against sprays or powders that can be inhaled, where IARC rates inhaled titanium dioxide as possibly carcinogenic.", [], [], ["SCCS", "IARC"]],
    ["good", ["xanthan gum"], "Thickener", "A natural-origin thickener that keeps a formula smooth.", [], [], ["COSING"]],
    ["good", ["disodium edta", "tetrasodium edta", "trisodium edta", "trisodium ethylenediamine disuccinate", "tetrasodium glutamate diacetate", "sodium phytate", "sodium gluconate"], "Stabilizer", "Binds metal ions to keep the formula stable.", [], [], ["COSING"]],
    ["good", ["ascorbic acid", "vitamin c", "sodium ascorbyl phosphate"], "Antioxidant, can sting on sensitive skin", "Brightens and protects. Stronger forms can sting or irritate sensitive skin.", ["irritation"], ["pigmentation", "lines"], ["COSING"]],
    ["good", ["dimethicone", "dimethiconol", "amodimethicone", "phenyl trimethicone", "trimethylsiloxysilicate", "dimethicone crosspolymer", "dimethicone/vinyl dimethicone crosspolymer", "cetyl peg/ppg-10/1 dimethicone", "bis-peg/ppg-14/14 dimethicone", "peg-10 dimethicone"], "Silicone that smooths skin", "Reviewed as safe in cosmetics. Some people with acne-prone skin prefer silicone-free products.", [], [], ["COSING"]],

    // mid
    ["mid", ["retinol", "retinyl palmitate", "retinal", "retinyl acetate", "retinyl linoleate", "hydroxypinacolone retinoate", "retinyl retinoate", "vitamin a"], "Effective but can irritate; ask a doctor if pregnant", "A vitamin A form used for lines, tone and acne. Start slowly and use sunscreen by day. Avoid when pregnant or breastfeeding unless your doctor says otherwise.", ["irritation", "pregnancy", "sun"], ["lines", "acne", "pigmentation"], ["SCCS", "MFDS", "MTB"]],
    ["mid", ["salicylic acid", "sodium salicylate", "betaine salicylate"], "Exfoliant, can dry or irritate", "Unclogs pores and is common in acne products. Can dry or irritate. EU rules limit how much is allowed and do not allow it in products for children under 3, except shampoo. Ask a doctor about strong peels if pregnant.", ["irritation", "drying"], ["acne"], ["SCCS", "MFDS", "COSING", "MHLW", "NMPA"]],
    ["mid", ["glycolic acid", "lactic acid", "mandelic acid", "malic acid", "tartaric acid"], "Exfoliating acid, raises sun sensitivity", "Smooths and brightens by exfoliating. Can sting and make skin more sensitive to sun, so use sunscreen.", ["irritation", "sun"], ["pigmentation", "lines"], ["COSING"]],
    ["mid", ["sodium laureth sulfate", "ammonium laureth sulfate", "ammonium lauryl sulfate", "sodium c14-16 olefin sulfonate", "sodium lauroyl sarcosinate", "sodium coco-sulfate", "tea-dodecylbenzenesulfonate"], "Cleansing agent, can dry the skin", "Foaming cleanser. Milder than SLS but can still dry or irritate sensitive skin.", ["irritation", "drying"], [], ["COSING"]],
    ["mid", ["cocamidopropyl betaine"], "Cleansing agent, can irritate sensitive skin", "A gentle foaming agent, but a known cause of contact allergy in some people, often linked to impurities.", ["allergy", "irritation"], [], ["COSING", "ACDS"]],
    ["mid", ["cocos nucifera oil", "cocos nucifera (coconut) oil", "coconut oil"], "Can clog pores for some skin", "Moisturizing, but rated comedogenic in older tests. The real-world effect varies, and acne-prone skin often reacts.", ["comedogenic"], ["dryness"], ["COSING"]],
    ["mid", ["isopropyl myristate"], "Can clog pores for some skin", "Gives a silky feel. Rated comedogenic in older tests, so acne-prone skin may prefer to avoid it.", ["comedogenic"], [], ["COSING"]],
    ["mid", ["menthyl lactate"], "Cooling, can irritate sensitive skin", "Gives a cooling sensation. Can irritate sensitive or damaged skin.", ["irritation"], [], ["COSING"]],
    ["mid", ["benzophenone-3", "oxybenzone"], "Chemical UV filter, known allergen for some", "Absorbs UV light. A known cause of contact and photo-allergy for some people, and restricted in some places for environmental reasons.", ["allergy"], [], ["SCCS", "EUREG", "MFDS", "MHLW", "NMPA"]],
    ["bad", ["dmdm hydantoin", "imidazolidinyl urea", "quaternium-15", "diazolidinyl urea", "sodium hydroxymethylglycinate", "bronopol", "2-bromo-2-nitropropane-1,3-diol"], "Preservative that releases small amounts of formaldehyde", "Formaldehyde is classified as a human carcinogen by IARC. These preservatives release tiny amounts, and the EU requires a label warning above a set level. They can cause contact allergy.", ["allergy", "cancer"], [], ["EUREG", "SCCS", "MFDS", "IARC", "ECHA", "MHLW", "NMPA"]],

    // bad
    ["mid", ["parfum", "fragrance", "aroma", "perfume", "fragrance / parfum", "parfum / fragrance", "parfum/fragrance", "fragrance(parfum)", "fragrance/parfum", "parfum (fragrance)", "fragrance (parfum)"], "Fragrance mix, common allergen", "A blend that can contain dozens of undisclosed substances. One of the most common causes of cosmetic allergy and irritation. The individual allergens the EU makes brands name (limonene, linalool and others) are flagged on their own.", ["allergy", "irritation"], [], ["EUREG", "SCCS", "MFDSF"], "fragrance"],
    ["bad", ["limonene", "linalool", "citronellol", "geraniol", "citral", "eugenol", "coumarin", "hexyl cinnamal", "benzyl salicylate", "benzyl alcohol", "alpha-isomethyl ionone", "amyl cinnamal", "cinnamal", "farnesol", "hydroxycitronellal", "benzyl benzoate", "benzyl cinnamate", "cinnamyl alcohol", "isoeugenol", "anise alcohol", "amylcinnamyl alcohol", "methyl 2-octynoate", "evernia prunastri extract", "evernia furfuracea extract", "acetyl cedrene", "amyl salicylate", "anethole", "benzaldehyde", "camphor", "beta-caryophyllene", "carvone", "dimethyl phenethyl acetate", "hexadecanolactone", "hexamethylindanopyran", "linalyl acetate", "trimethylcyclopentenyl methylisopentenol", "salicylaldehyde", "santalol", "sclareol", "terpineol", "tetramethyl acetyloctahydronaphthalenes", "trimethylbenzenepropanol", "vanillin", "geranyl acetate", "eugenyl acetate", "isoeugenyl acetate", "pinene", "alpha-pinene", "beta-pinene", "6-methylcoumarin", "6-methyl coumarin", "cananga odorata flower extract", "cananga odorata flower oil", "cinnamomum cassia leaf oil", "cinnamomum zeylanicum bark oil", "citrus aurantium amara flower oil", "citrus aurantium amara peel oil", "citrus limon peel oil", "cymbopogon schoenanthus oil", "eucalyptus globulus leaf oil", "eugenia caryophyllus leaf oil", "juniperus virginiana oil", "juniperus virginiana wood oil", "laurus nobilis leaf oil", "mentha piperita oil", "peppermint oil", "mentha viridis leaf oil", "narcissus poeticus extract", "pelargonium graveolens flower oil", "pogostemon cablin oil", "santalum album oil", "pinus mugo leaf oil", "pinus mugo twig oil", "pinus pumila needle extract", "pinus pumila twig leaf oil", "cedrus atlantica bark oil", "cedrus atlantica wood oil", "cedrus atlantica leaf extract", "turpentine", "alpha-terpinene", "terpinolene", "myroxylon pereirae resin", "myroxylon pereirae oil", "myroxylon balsamum pereirae balsam oil", "alpha-damascone", "rose ketone 4", "rose ketone 3", "3-propylidenephthalide", "lippia citriodora absolute", "methyl salicylate", "citrus aurantium peel oil", "citrus aurantium dulcis flower oil", "hexyl salicylate", "d-limonene", "dl-limonene", "rose ketone-4", "rose ketone-3"], "Fragrance allergen", "One of the fragrance substances the EU requires to be named on the label because it can cause contact allergy (above 0.001% in leave-on and 0.01% in rinse-off products). The EU list grew from 26 to 80 substances in 2023: new products must follow it since 31 July 2026, and all products from 31 July 2028. Korea also requires labeling a similar list since 2020.", ["allergy"], [], ["EUREG", "SCCS", "MFDSF"], "fragrance"],
    // 6 Oct 2026 (night), decision of Fernanda: sweet orange peel oil (citrus aurantium dulcis / citrus sinensis peel oil) and D4 (cyclotetrasiloxane) also go to "to watch" (see the entries below and further down). OnSkin gave Dr. Althea Gentle Bubble Cleanser Amino Acid 98 with orange peel oil alone and no declared limonene.
    // 6 Oct 2026, decision of Fernanda: these five families (menthol, rose, jasmine, lavender and bergamot) go from "flagged" to "to watch". They are on the EU's expanded fragrance allergen list, but OnSkin does not flag them and, on 105 Kundal and anillO products, rating them "to watch" brings our score within 5 points of OnSkin on 100 of 105 (mean error 1.6, was 14.9).
    ["mid", ["menthol"], "Cooling agent, EU fragrance allergen", "Gives the cool, minty feel. The EU now asks makers to name it on the label because it can cause contact allergy in some people, and it can irritate sensitive skin or scalp. We rate it \"to watch\" rather than flagged.", ["allergy", "irritation"], [], ["EUREG", "SCCS", "MFDSF"], "fragrance"],
    ["mid", ["citrus aurantium bergamia peel oil", "citrus aurantium bergamia fruit oil", "jasminum grandiflorum flower extract", "jasminum officinale oil", "jasminum officinale flower extract", "lavandula angustifolia oil", "lavandula angustifolia flower/leaf/stem extract", "rosa damascena flower oil", "rosa damascena flower extract", "rosa centifolia flower oil", "rosa centifolia flower extract", "rosa canina flower oil", "rosa alba flower oil", "rosa alba flower extract", "rosa gallica flower oil", "rosa moschata flower oil", "rosa rugosa flower oil", "citrus aurantium dulcis peel oil", "citrus aurantium dulcis oil", "citrus sinensis peel oil"], "Botanical fragrance ingredient, EU allergen list", "A flower or essential-oil ingredient used for scent. It is on the EU's expanded fragrance allergen list (2023), which asks makers to name it on the label because it can cause contact allergy in some people. We rate it \"to watch\" rather than flagged: it is a natural component, usually present in small amounts.", ["allergy"], [], ["EUREG", "SCCS", "MFDSF"], "fragrance"],
    ["bad", ["butylphenyl methylpropional", "lilial", "butylphenyl methyl propional", "butylphenyl methyl-propional", "butyl phenyl methylpropional"], "Banned in EU cosmetics", "Linked to reproductive toxicity and banned in EU cosmetics since 2022. If you still see it, the product may be old or made for another market.", ["hormone", "restricted"], [], ["SCCS", "EUREG", "ECHA"]],
    ["mid", ["alcohol denat.", "alcohol denat", "sd alcohol", "sd alcohol 40-b", "denatured alcohol", "ethanol", "alcohol"], "Drying and irritating", "Ethanol evaporates fast and can dry out the skin barrier, especially high on the ingredient list. Not banned or restricted in the EU, but dry and sensitive skin tend to react.", ["irritation", "drying"], [], ["COSING"]],
    ["mid", ["sodium lauryl sulfate"], "Strong cleanser, can dry and irritate", "A harsh foaming agent. Allowed in the EU and reviewed as safe in rinse-off products, but it is a known skin irritant.", ["irritation", "drying"], [], ["COSING"]],
    ["bad", ["methylisothiazolinone", "methylchloroisothiazolinone"], "Preservative, common contact allergen", "A well-known cause of contact allergy. The EU does not allow these preservatives in leave-on products.", ["allergy", "restricted"], [], ["SCCS", "EUREG", "MFDS", "MHLW", "NMPA"]],
    ["bad", ["triclosan"], "Antibacterial, restricted in many places", "Antibacterial agent restricted in EU cosmetics and banned from US consumer hand soaps. Concerns include hormone disruption and antibiotic resistance.", ["hormone", "restricted"], [], ["SCCS", "EUREG", "MFDS", "ECHA", "MHLW", "NMPA"]],

    // ---- expansion (formula basics, based on what appears most in real products) ----
    ["good", ["citric acid", "sodium citrate", "aminomethyl propanol", "aminomethyl propanediol"], "pH adjuster", "Balances the acidity of a formula. At the low levels used for this, it is not a concern.", [], [], ["COSING"]],
    ["good", ["sodium hydroxide", "potassium hydroxide"], "pH adjuster", "Used in tiny amounts to balance acidity and fully neutralized in the finished product.", [], [], ["COSING"]],
    ["bad", ["phenoxyethanol"], "Preservative, capped at 1% in the EU", "A widely used preservative. The EU limits it to 1% of the product, and EU scientists consider that level safe. French regulators advise against it in leave-on products for the diaper area of children under 3. A small number of people find it irritating.", ["restricted", "irritation"], [], ["SCCS", "EUREG", "MFDS", "MHLW", "NMPA"]],
    ["good", ["sodium benzoate", "potassium sorbate", "benzoic acid", "sorbic acid", "dehydroacetic acid", "sodium dehydroacetate", "chlorphenesin", "caprylhydroxamic acid", "sodium levulinate", "o-cymen-5-ol"], "Gentle preservative", "Preservatives used at low levels and allowed in the EU within set limits. Rarely irritating.", ["restricted"], [], ["EUREG", "COSING", "MHLW", "NMPA"]],
    ["good", ["ethylhexylglycerin"], "Preservative booster that softens skin", "Helps preservatives work and leaves skin soft. Contact allergy is uncommon.", [], [], ["COSING"]],
    ["good", ["hydroxyacetophenone"], "Preservative booster, soothing", "Helps preserve the formula and has a mild calming effect. Well tolerated.", [], ["redness"], ["COSING"]],
    ["good", ["sodium chloride", "magnesium sulfate"], "Salt, thickener", "Thickens cleansers and adjusts texture. No concerns at these levels.", [], [], ["COSING"]],
    ["good", ["caprylic/capric triglyceride", "coco-caprylate/caprate", "coco-caprylate", "dicaprylyl carbonate", "dicaprylyl ether", "ethylhexyl palmitate", "ethylhexyl stearate", "c12-15 alkyl benzoate", "octyldodecanol", "dibutyl adipate", "diisostearyl malate", "myristyl myristate", "cetyl palmitate", "cetyl esters", "glyceryl oleate", "triethyl citrate", "hydrogenated polyisobutene", "isohexadecane", "isononyl isononanoate", "bis-diglyceryl polyacyladipate-2", "propylene carbonate", "jojoba esters", "hydrogenated coco-glycerides", "butyloctyl salicylate", "diisopropyl sebacate", "polybutene", "isododecane", "tribehenin", "glyceryl caprylate", "hydrogenated palm glycerides citrate", "polyglyceryl-2 triisostearate", "bis-behenyl/isostearyl/phytosteryl dimer dilinoleyl dimer dilinoleate", "triethylhexanoin", "cetyl ethylhexanoate", "pentaerythrityl tetraethylhexanoate", "pentaerythrityl tetraisostearate", "pentaerythrityl distearate", "decyl oleate", "diisopropyl adipate", "tridecyl trimellitate", "diethylhexyl succinate", "triolein", "c10-18 triglycerides", "butylene glycol dicaprylate/dicaprate", "hexyl laurate", "octyldodecyl myristate", "isostearyl alcohol", "isostearic acid", "lauric acid", "oleic acid", "arachidic acid", "capric acid", "hydroxystearic acid", "hydrogenated poly(c6-14 olefin)", "hydrogenated polydecene", "polyisobutene", "c14-22 alcohols", "phytosphingosine", "phytosteryl macadamiate", "phytosteryl/behenyl/octyldodecyl lauroyl glutamate", "phytosteryl/octyldodecyl lauroyl glutamate", "phytosteryl isostearyl dimer dilinoleate", "brassica campestris sterols", "glycine soja sterols", "sodium metabisulfite"], "Emollient", "Softens skin and improves how a product spreads. Widely used and generally well tolerated.", [], [], ["COSING"]],
    ["good", ["propylene glycol"], "Humectant and solvent", "Draws in water and helps ingredients dissolve. Can sting or, rarely, cause allergy, especially on damaged skin.", ["irritation"], ["dryness"], ["COSING"]],
    ["good", ["butylene glycol", "pentylene glycol", "propanediol", "1,2-hexanediol", "caprylyl glycol", "dipropylene glycol", "hexylene glycol", "methylpropanediol", "glycereth-26", "isopentyldiol", "1,2-hexandiol", "octanediol", "benzyl glycol"], "Humectant and solvent", "Draws in water and helps other ingredients dissolve. Gentler than propylene glycol for most people.", [], ["dryness"], ["COSING"]],
    ["good", ["sodium pca", "betaine", "trehalose", "sodium lactate", "sorbitol", "xylitol", "polyglutamic acid", "glycine", "arginine", "serine", "proline", "glucose", "fructose", "sucrose", "mannitol", "histidine", "fructooligosaccharides", "pantolactone", "biosaccharide gum-1", "decylene glycol", "triethylene glycol", "peg-8", "aqua / water", "alanine", "phenylalanine", "threonine", "isoleucine", "valine", "leucine", "lysine", "tyrosine", "methionine", "cysteine", "glutamic acid", "aspartic acid", "pca", "erythritol", "inositol", "ectoin", "carnosine", "hydroxyethyl urea", "sodium polyglutamate", "hydroxypropyl cyclodextrin", "methyl gluceth-10", "glyceryl glucoside", "anhydroxylitol", "maltitol", "rhamnose", "sodium dna", "acetyl glucosamine", "panthenyl ethyl ether", "pantethine", "glycyl glycine", "glucosyl hesperidin", "sodium heparin", "tremella fuciformis polysaccharide", "tremella fuciformis sporocarp polysaccharide", "recombinant human collagen", "hydrolyzed collagen", "collagen", "ergothioneine", "hydrolyzed pearl", "pearl powder", "margarita powder"], "Humectant", "Holds water in the skin. Naturally found in skin or very similar to it, and well tolerated.", [], ["dryness"], ["COSING"]],
    ["good", ["urea"], "Humectant, softens rough skin", "Hydrates and gently softens rough, dry skin. Can sting on broken skin or at high strengths.", ["irritation"], ["dryness"], ["COSING"]],
    ["good", ["glyceryl stearate", "glyceryl stearate se", "glyceryl stearate citrate", "stearic acid", "palmitic acid", "myristic acid", "behenyl alcohol", "cetearyl glucoside", "lecithin", "hydrogenated lecithin", "polysorbate 20", "polysorbate 60", "polysorbate 80", "ceteareth-20", "peg-100 stearate", "peg-40 hydrogenated castor oil", "steareth-2", "steareth-20", "glycol distearate", "peg-7 glyceryl cocoate", "sorbitan isostearate", "sorbitan olivate", "sorbitan oleate", "potassium cetyl phosphate", "sodium stearoyl glutamate", "hydrogenated castor oil", "sodium cetearyl sulfate", "trideceth-10", "cetearyl olivate", "steareth-21", "arachidyl alcohol", "arachidyl glucoside", "peg-6 caprylic/capric glycerides", "polyhydroxystearic acid", "myristyl alcohol", "laureth-2", "caprylyl/capryl glucoside", "disodium cocoyl glutamate", "microcrystalline wax"], "Emulsifier or thickener", "Helps oil and water mix into a smooth cream. Common and well tolerated. PEG-based ones are considered safe when manufacturers keep impurities low.", [], [], ["COSING"]],
    ["good", ["carbomer", "acrylates/c10-30 alkyl acrylate crosspolymer", "acrylates copolymer", "sodium polyacrylate", "hydroxyethylcellulose", "cellulose gum", "microcrystalline cellulose", "guar hydroxypropyltrimonium chloride", "polyquaternium-10", "disteardimonium hectorite", "acrylamide/sodium acryloyldimethyltaurate copolymer", "hydroxyethyl acrylate/sodium acryloyldimethyl taurate copolymer", "polyacrylate crosspolymer-6", "polyquaternium-7", "inulin", "sodium xylenesulfonate", "dextrin", "zea mays starch", "carrageenan", "succinoglycan", "ceratonia siliqua gum", "tapioca starch", "cyamopsis tetragonoloba gum", "gellan gum", "glucomannan", "chondrus crispus powder", "hydroxypropyl starch phosphate", "hydroxypropyl methylcellulose", "ethylcellulose", "dextrin palmitate", "aluminum/magnesium hydroxide stearate", "sodium metaphosphate", "potassium chloride", "distarch phosphate", "pvp", "polyquaternium-51", "polyquaternium-39"], "Thickener", "Gives gels and creams their body. Well tolerated.", [], [], ["COSING"]],
    ["good", ["silica", "mica", "kaolin", "silica dimethyl silylate", "triethoxycaprylylsilane", "maltodextrin", "aluminum starch octenylsuccinate", "magnesium aluminum silicate", "aluminum hydroxide", "alumina", "charcoal powder", "magnesium chloride", "calcium chloride", "disodium phosphate", "potassium phosphate", "tromethamine", "levulinic acid", "p-anisic acid", "magnesium nitrate", "polymethylsilsesquioxane", "boron nitride", "synthetic fluorphlogopite", "hydrated silica"], "Mineral texture ingredient", "Absorbs oil and adds a soft feel. Avoid breathing in loose powders.", [], [], ["COSING"]],
    ["good", ["ci 77491", "ci 77492", "ci 77499", "iron oxides"], "Iron oxide pigment", "Mineral pigment used in tinted products and sunscreens. Well tolerated.", [], [], ["SCCS", "COSING"]],
    ["good", ["ci 42090", "ci 19140", "ci 17200", "ci 15850", "ci 15985", "ci 16035", "ci 14700", "ci 47005", "ci 60730", "ci 60725", "ci 26100", "ci 15510", "ci 16185", "ci 47000", "ci 42053", "ci 61570", "blue 1", "blue 1 lake", "yellow 5", "yellow 5 lake", "yellow 6", "yellow 6 lake", "red 40", "red 40 lake", "green 3"], "Color additive", "A color additive on the EU approved list. Rarely causes a reaction.", [], [], ["EUREG", "COSING"]],
    ["good", ["aluminum chlorohydrate", "aluminum chloride"], "Antiperspirant, EU-capped", "Blocks sweat. EU scientists consider it safe in deodorants and antiperspirants up to a set aluminum level; avoid on broken skin.", ["restricted"], [], ["SCCS", "EUREG"]],
    ["good", ["propane", "butane", "isobutane"], "Propellant gas", "Pushes a spray out of the can and evaporates. Avoid breathing in sprays.", [], [], ["COSING"]],
    ["good", ["helianthus annuus seed oil", "simmondsia chinensis seed oil", "argania spinosa kernel oil", "prunus amygdalus dulcis oil", "ricinus communis seed oil", "olea europaea fruit oil", "persea gratissima oil", "vitis vinifera seed oil", "rosa canina fruit oil", "squalene", "oryza sativa bran oil", "camellia oleifera seed oil", "glycine soja oil", "hydrogenated rapeseed oil", "helianthus annuus hybrid oil", "mangifera indica seed butter", "glycine soja"], "Plant oil", "Softens skin and helps seal in moisture. Nut-based oils matter if you have a nut allergy.", [], ["dryness"], ["COSING"]],
    ["good", ["cera alba", "beeswax", "copernicia cerifera cera", "cera microcristallina", "synthetic wax", "candelilla cera", "euphorbia cerifera cera"], "Wax", "Adds body and a protective feel. Allergy to beeswax is rare.", [], [], ["COSING"]],
    ["bad", ["paraffinum liquidum", "petrolatum", "paraffin", "mineral oil"], "Petroleum-based occlusive, safe only if highly refined", "Seals in moisture well. Cosmetic grades are highly refined, but IARC rates untreated and mildly treated mineral oils as carcinogenic, so the EU only allows these ingredients when their refining history is known and shows the contaminants (PAHs) are removed. The package can't tell you the grade.", ["restricted"], ["dryness"], ["IARC", "EUREG"]],
    ["good", ["pentaerythrityl tetra-di-t-butyl hydroxyhydrocinnamate", "ascorbyl palmitate"], "Antioxidant for the formula", "Keeps oils from going rancid. No regulatory concerns at the levels used; a few people are sensitive.", [], [], ["COSING"]],
    ["good", ["ethylhexyl triazone", "bis-ethylhexyloxyphenol methoxyphenyl triazine", "diethylamino hydroxybenzoyl hexyl benzoate", "butyl methoxydibenzoylmethane", "ethylhexyl salicylate", "phenylbenzimidazole sulfonic acid", "methylene bis-benzotriazolyl tetramethylbutylphenol", "drometrizole trisiloxane", "terephthalylidene dicamphor sulfonic acid", "tris-biphenyl triazine", "diethylhexyl butamido triazone", "isoamyl p-methoxycinnamate"], "UV filter", "Absorbs UV light. Allowed in the EU and Korea within set limits. Newer filters like these are well tolerated by most people.", ["restricted"], [], ["SCCS", "EUREG", "MFDS", "MHLW", "NMPA"]],
    ["good", ["bisabolol", "adenosine", "caffeine", "ubiquinone", "ferulic acid", "resveratrol", "camellia sinensis leaf extract", "glycyrrhiza glabra root extract", "dipotassium glycyrrhizate", "ammonium glycyrrhizate", "avena sativa kernel flour", "avena sativa kernel extract", "sodium carboxymethyl betaglucan", "beta-glucan", "zinc pca", "zinc gluconate", "phytic acid", "rosmarinus officinalis leaf extract", "calendula officinalis flower extract", "chamomilla recutita flower extract", "biotin", "scutellaria baicalensis root extract", "nelumbo nucifera flower extract", "nelumbo nucifera leaf extract", "betula platyphylla japonica juice", "betula platyphylla japonica bark extract", "paeonia lactiflora root extract", "paeonia albiflora root extract", "paeonia suffruticosa root extract", "rehmannia glutinosa root extract", "panax ginseng flower extract", "panax notoginseng root extract", "hydrolyzed ginseng saponins"], "Skin-calming or antioxidant active", "Soothes or protects skin. Well tolerated by most people, and allergy is uncommon.", [], ["redness", "lines"], ["COSING"]],
    ["good", ["snail secretion filtrate", "houttuynia cordata extract", "artemisia princeps leaf extract", "artemisia vulgaris extract", "panax ginseng root extract", "galactomyces ferment filtrate", "saccharomyces ferment filtrate", "bifida ferment lysate", "lactobacillus ferment", "oryza sativa germ extract", "oryza sativa bran extract", "asiaticoside", "madecassic acid", "asiatic acid", "centella asiatica leaf water"], "Popular K-beauty soothing or hydrating ingredient", "Common in Korean skincare for calming and hydrating. No regulatory concerns, and allergy is rare.", [], ["redness", "dryness"], ["COSING", "MFDS"]],
    ["good", ["ascorbyl glucoside", "magnesium ascorbyl phosphate", "ethyl ascorbic acid", "3-o-ethyl ascorbic acid", "tetrahexyldecyl ascorbate"], "Gentler vitamin C", "A stable vitamin C form that brightens and protects with less stinging than pure ascorbic acid.", [], ["pigmentation", "lines"], ["COSING"]],
    ["good", ["avobenzone", "octisalate", "ethylhexyl salicylate"], "UV filter", "Absorbs UV light. Allowed in the EU and Korea within set limits.", ["restricted"], [], ["SCCS", "EUREG", "MFDS"]],

    ["good", ["phytosterols", "beta-sitosterol", "phospholipids", "glycolipids", "canola oil", "oenothera biennis oil", "hippophae rhamnoides oil", "hydrogenated olive oil unsaponifiables", "glyceryl linolenate", "glyceryl behenate", "c13-15 alkane", "hydroxypropyl bispalmitamide mea", "lauroyl lysine", "stearalkonium hectorite", "cyclodextrin", "dextran", "agar", "xylose", "hydrolyzed corn starch", "hydrolyzed potato protein", "atelocollagen", "royal jelly", "dipotassium phosphate", "calcium gluconate", "tin oxide", "calcium aluminum borosilicate", "bakuchiol", "astaxanthin", "tropolone", "lactobacillus", "chamaecyparis obtusa water"], "Skin-friendly helper or oil", "Lipids, plant oils, sugars, proteins and texture helpers. Generally well tolerated; plant oils and royal jelly can trigger allergy in a few people.", [], [], ["COSING"]],

    ["good", ["alpha-arbutin"], "Brightening active", "Used to fade dark spots. The EU sets a maximum level in face products. A 2025 lab-model study from China Pharmaceutical University found skin bacteria can convert it into hydroquinone, which the EU does not allow in skin lighteners; this is early evidence and regulators still allow alpha-arbutin within the limit.", ["restricted"], ["pigmentation"], ["SCCS", "COSING", "CPU"]],
    ["good", ["tranexamic acid"], "Brightening active", "Used to fade dark spots and uneven tone. Well tolerated by most people.", [], ["pigmentation"], ["COSING"]],
    ["good", ["azelaic acid"], "Calms redness and breakouts", "Used for acne, redness and dark spots. Can sting a little when you start.", ["irritation"], ["acne", "redness", "pigmentation"], ["COSING"]],
    ["good", ["gluconolactone", "lactobionic acid"], "Gentle exfoliating acid (PHA)", "A milder exfoliant than glycolic acid that also hydrates. Usually suits sensitive skin.", [], ["lines", "pigmentation"], ["COSING"]],
    ["good", ["palmitoyl tripeptide-1", "palmitoyl tetrapeptide-7", "acetyl hexapeptide-8", "palmitoyl pentapeptide-4", "copper tripeptide-1", "palmitoyl tripeptide-5", "myristoyl pentapeptide-17", "tripeptide-1"], "Peptide", "Short chains of amino acids used in anti-aging products. Well tolerated, though evidence for results varies.", [], ["lines"], ["COSING"]],
    ["good", ["piroctone olamine"], "Anti-dandruff agent", "Used in dandruff shampoos. The EU caps how much is allowed.", ["restricted"], [], ["SCCS", "EUREG"]],
    ["good", ["coco-glucoside", "decyl glucoside", "lauryl glucoside", "sodium cocoyl glycinate", "sodium cocoyl glutamate", "sodium cocoyl isethionate", "disodium cocoamphodiacetate", "cocamidopropyl hydroxysultaine", "sodium lauroyl glutamate", "cocamide mea", "sodium methyl cocoyl taurate", "sodium taurine cocoyl methyltaurate", "sodium methyl stearoyl taurate", "potassium cocoyl glycinate", "sodium cocoyl alaninate", "lauryl betaine", "lauryl hydroxysultaine", "quillaja saponaria bark extract"], "Mild cleansing agent", "A gentle foaming agent that cleans without stripping as much as sulfates do.", [], [], ["COSING"]],
    ["mid", ["isopropyl palmitate", "isopropyl isostearate"], "Can clog pores for some skin", "An emollient rated comedogenic in older tests, so acne-prone skin may prefer to avoid it.", ["comedogenic"], [], ["COSING"]],
    ["mid", ["theobroma cacao seed butter", "cocoa butter"], "Rich butter, can clog pores for some", "Very softening but rated comedogenic in older tests. Acne-prone skin may react.", ["comedogenic"], ["dryness"], ["COSING"]],
    ["mid", ["cyclopentasiloxane", "cyclohexasiloxane", "cyclomethicone"], "Silicone solvent, EU-restricted", "The EU already limits these silicones to 0.1% in rinse-off products, and from 6 June 2027 in all cosmetics, because they persist in the environment. This is about the environment, not a skin reaction.", ["restricted"], [], ["EUREG", "SCCS"]],
    ["mid", ["lanolin", "lanolin alcohol"], "Rich emollient, known allergen for some", "Softens very dry skin but is a well-known cause of contact allergy, especially on damaged skin.", ["allergy"], ["dryness"], ["COSING", "ACDS"]],
    ["mid", ["propolis extract", "propolis cera"], "Bee product, can cause allergy", "Soothing for some, but propolis is a known contact allergen, especially if you react to bee products or balsam of Peru.", ["allergy"], [], ["COSING", "ACDS"]],
    ["bad", ["triethanolamine"], "pH adjuster, EU-regulated", "Used to balance acidity. The EU limits it and advises not to combine it with ingredients that can form nitrosamines. Can irritate sensitive skin.", ["restricted", "irritation"], [], ["EUREG", "SCCS"]],
    ["bad", ["methylparaben", "ethylparaben", "sodium methylparaben", "sodium ethylparaben", "potassium methylparaben", "potassium ethylparaben"], "Preservative, EU-limited", "A preservative the EU allows up to 0.4% each (0.8% total). Debated for hormone-like activity at high doses, though EU scientists consider these limits safe.", ["restricted"], [], ["SCCS", "EUREG", "MFDS", "MHLW", "NMPA"]],
    ["bad", ["propylparaben", "butylparaben", "sodium propylparaben", "sodium butylparaben", "potassium propylparaben", "potassium butylparaben"], "Preservative, EU limit lowered", "The EU lowered the limit to 0.14% in 2014 because of hormone-related concerns, and bars them from nappy-area products for children under 3.", ["restricted", "hormone"], [], ["SCCS", "EUREG", "MFDS", "ECHA", "MHLW", "NMPA"]],
    ["bad", ["iodopropynyl butylcarbamate"], "Preservative, restricted", "The EU restricts it and does not allow it in lip products, body lotions or products for children under 3. Can cause contact allergy.", ["allergy", "restricted"], [], ["SCCS", "EUREG", "MHLW", "NMPA"]],
    ["mid", ["cocamide dea"], "Foam booster, cancer concern", "IARC rates it as possibly carcinogenic (group 2B), and DEA-type ingredients can form nitrosamines. Also a skin irritant for some.", ["irritation", "cancer"], [], ["IARC", "EUREG", "ECHA"]],
    ["mid", ["talc"], "Mineral powder, inhalation concern", "IARC rates talc as probably carcinogenic (group 2A). The concern is mainly breathing it in and asbestos contamination in unpurified talc.", ["cancer"], [], ["IARC", "SCCS", "ECHA"]],
    ["bad", ["homosalate", "ethylhexyl methoxycinnamate", "octinoxate"], "UV filter under review", "EU scientists have raised hormone-related concerns about these UV filters, and limits are being tightened. Octinoxate is also restricted in some places to protect reefs.", ["hormone", "restricted"], [], ["SCCS", "EUREG", "ECHA", "MHLW", "NMPA"]],
    ["mid", ["kojic acid"], "Brightening active, restricted", "Used to fade dark spots. The EU allows it up to 1% in face and hand products. Can irritate or cause contact allergy.", ["restricted", "irritation", "allergy"], ["pigmentation"], ["SCCS", "EUREG"]],
    ["mid", ["hamamelis virginiana water", "hamamelis virginiana leaf water", "hamamelis virginiana extract", "hamamelis virginiana leaf extract"], "Witch hazel, astringent", "Tightens and refreshes oily skin, but often contains alcohol and can dry or irritate sensitive skin.", ["irritation", "drying"], [], ["COSING"]],
    ["mid", ["citrus aurantifolia oil", "citrus aurantifolia peel oil", "citrus grandis peel oil", "melaleuca alternifolia leaf oil", "pelargonium graveolens oil", "rosmarinus officinalis leaf oil", "anthemis nobilis flower oil", "pinus sylvestris leaf oil", "pinus palustris leaf oil", "leptospermum petersonii oil", "abies sibirica oil", "pinus palustris oil", "juniperus mexicana oil", "mentha arvensis leaf oil", "eucalyptus dives leaf oil", "lavandula spica flower oil", "cymbopogon martini oil", "salvia officinalis oil", "litsea cubeba fruit oil"], "Essential oil, can cause allergy", "Natural, but essential oils contain fragrance allergens such as limonene and linalool, and citrus oils can make skin sensitive to sun.", ["allergy"], [], ["EUREG", "COSING"]],
    ["mid", ["polymethyl methacrylate", "methyl methacrylate crosspolymer"], "Plastic particles, EU is phasing out", "Tiny plastic particles used for a smooth, blurring feel. The EU is restricting intentionally added microplastics because they persist in the environment.", ["restricted"], [], ["EUREG"]],
    ["mid", ["hydrolyzed wheat protein", "hydrolyzed wheat gluten"], "Wheat protein, rare but serious allergy", "In Japan, a face soap made with a hydrolyzed wheat protein caused wheat allergy through the skin in more than 2,000 people (reported 2010 to 2011), and the Japanese Society of Allergology set up a special committee on it. It is not common, but if you have wheat allergy, check labels.", ["allergy"], [], ["NIHS", "FUJITA", "ACDS"]],
    ["mid", ["carmine", "ci 75470", "cochineal", "carminic acid", "cochineal extract"], "Insect-derived red dye, can cause allergy", "A red dye from cochineal insects used in lipstick and eyeshadow. Skin contact can sensitize some people, who may later react to foods colored with it. Japanese allergy doctors and the Food Safety Commission have documented cases.", ["allergy"], [], ["EUREG", "FSC", "PSJ"]],
    ["mid", ["isopropyl alcohol"], "Drying alcohol", "Evaporates quickly and can dry out or irritate the skin barrier.", ["irritation", "drying"], [], ["COSING"]],
    ["bad", ["isopropylparaben", "isobutylparaben", "phenylparaben", "benzylparaben", "pentylparaben"], "Banned in EU cosmetics", "These parabens have been banned in EU cosmetics since 2014 because there was not enough safety data.", ["restricted", "hormone"], [], ["SCCS", "EUREG", "ECHA", "MHLW", "NMPA"]],
    ["bad", ["hydroxyisohexyl 3-cyclohexene carboxaldehyde", "hicc", "lyral"], "Banned fragrance allergen", "A strong fragrance sensitizer. The EU banned it in cosmetics: new products from August 2019 and all sales from August 2021.", ["allergy", "restricted"], [], ["SCCS", "EUREG"]],
    ["bad", ["tpo", "trimethylbenzoyl diphenylphosphine oxide"], "Banned in EU cosmetics since 2025", "A nail-polish and gel-nail ingredient the EU banned in cosmetics from September 2025 because of reproductive toxicity concerns. It still shows up in many alerts for imported products.", ["hormone", "restricted"], [], ["EUREG", "SCCS", "ECHA"]],
    ["bad", ["hydroquinone"], "Not allowed in EU skin lighteners", "A skin-lightening agent the EU does not allow in cosmetics for the skin because of safety concerns, including skin damage with long use.", ["restricted"], [], ["SCCS", "EUREG", "MHLW", "NMPA"]],

    ["mid", ["cyclotetrasiloxane", "octamethylcyclotetrasiloxane"], "Silicone D4, restricted in the EU", "A silicone known as D4. The EU lists it among the substances banned in cosmetics (it is classified as possibly toxic to reproduction, category 2) and it also persists in the environment. Only technically unavoidable traces are tolerated. We rate it \"to watch\" rather than flagged because OnSkin rates it as moderate risk (decision of 6 Oct 2026, based on Huxley Secret of Sahara Essence: OnSkin 49).", ["hormone", "restricted"], [], ["EUREG", "ECHA"]],

    ["bad", ["pentasodium pentetate", "pentetic acid"], "Banned in EU cosmetics since 2023", "A chelating agent (it binds metal ions so the formula stays stable). The EU classified it as toxic to reproduction (category 1B) and banned it in cosmetics from 1 December 2023. Products made for other markets can still contain it.", ["hormone", "restricted"], [], ["EUREG", "ECHA"]],

    ["bad", ["sodium borate", "borax", "boric acid", "disodium tetraborate", "disodium octaborate", "zinc borate", "potassium borate", "tetraborate"], "Banned in EU cosmetics", "Boric acid and the borates (borax) are classified as toxic to reproduction (category 1B) and are on the EU list of substances banned in cosmetics. Products made for other markets can still contain them.", ["hormone", "restricted"], [], ["EUREG", "ECHA"]],

    ["bad", ["p-phenylenediamine", "p-aminophenol"], "Hair dye ingredient, strong allergen", "Used in permanent hair dyes. The EU allows it only in oxidative hair dyes, with a maximum on the hair and a mandatory allergy warning on the label. It is among the most common causes of hair-dye allergy: do the patch test the box asks for.", ["allergy", "restricted"], [], ["SCCS", "EUREG", "ACDS"]],

    ["mid", ["basic yellow 87", "basic red 51", "acid orange 7", "acid yellow 23"], "Hair colour dye, limited by the EU", "A direct hair dye (no mixing needed). The EU sets a maximum for these dyes in non-oxidative hair dyes; the amount left in a conditioner or shampoo is small. A few people react to hair dyes.", ["allergy", "restricted"], [], ["SCCS", "EUREG"]],

    ["mid", ["hydrogen peroxide"], "Bleaching agent, limited by the EU", "Lightens hair and is used in hair colour. The EU caps it in hair products and requires warnings. It can irritate the scalp and eyes.", ["irritation", "restricted"], [], ["EUREG"]],

    ["mid", ["benzoyl peroxide"], "Acne treatment, strong and drying", "Kills acne bacteria and unclogs pores, but it can dry, redden and peel skin and bleaches fabric. In the EU cosmetics rules it is listed only for professional artificial-nail systems; skin products with it are generally sold as medicines. Sun protection matters while using it.", ["irritation", "drying", "restricted"], ["acne"], ["EUREG", "ACDS"]],

    ["mid", ["benzalkonium chloride", "cetrimonium bromide"], "Disinfectant ingredient, limited by the EU", "A quaternary ammonium compound used as a preservative or conditioning agent. The EU limits it (0.1% as preservative) because it can irritate skin and eyes.", ["irritation", "restricted"], [], ["EUREG", "COSING"]],

    ["good", ["arbutin"], "Brightening active", "Used to fade dark spots. The EU allows up to 7% in face creams and asks that hydroquinone stays at unavoidable trace levels.", ["restricted"], ["pigmentation"], ["SCCS", "COSING"]],
    ["bad", ["bht", "butylated hydroxytoluene"], "Antioxidant, hormone concern, EU-limited", "A preservative-antioxidant. The EU safety committee (SCCS, 2021) judged it safe at up to 0.8% in leave-on and rinse-off products (0.1% in toothpaste, 0.001% in mouthwash) while noting concerns about possible hormone-like activity. A few people are sensitive.", ["hormone", "restricted"], [], ["SCCS", "EUREG"]],
    ["bad", ["octocrylene"], "UV filter, EU-limited, hormone concern", "A chemical UV filter. The EU allows up to 10% and its safety committee (SCCS, 2021) judged that safe while noting concerns about possible hormone-like activity. It can also break down into benzophenone over time.", ["hormone", "restricted"], [], ["SCCS", "EUREG", "ECHA"]],
    ["bad", ["carbon black", "ci 77266", "ci 77266 [nano]", "ci 77266 nano", "black 2", "carbon black (ci 77266)"], "Black pigment, possible carcinogen if inhaled", "Used in eyeliner, mascara and brow products. IARC rates carbon black as possibly carcinogenic to humans (group 2B), based on inhaled dust. The EU allows it in cosmetics (the nano form up to 10%) but not where it could be inhaled, such as sprays or loose powders.", ["cancer", "restricted"], [], ["IARC", "SCCS", "EUREG"], null, true],
    ["bad", ["mercury", "mercurous chloride", "ammoniated mercury", "ammonium mercuric chloride", "mercuric chloride"], "Mercury, banned in cosmetics", "Mercury compounds are banned in skin products in the EU and the US. They are toxic and can damage the kidneys and nerves.", ["restricted"], [], ["SCCS", "EUREG", "MHLW", "NMPA"]],
    // Added 1 Oct 2026 after measuring Korean-market catalog lists. Written from general cosmetic-chemistry knowledge, not verified one by one.
    ["good", ["ethyl hexanediol", "2,3-butanediol", "polyglycerin-3", "diglycerin", "fructan", "glutathione", "cyanocobalamin"], "Hydrating helper", "A humectant, solvent or skin-conditioning ingredient. Well tolerated at cosmetic levels.", [], ["dryness"], ["COSING"]],
    ["good", ["cellulose", "polyether-1", "inulin lauryl carbamate", "polyvinyl alcohol", "pullulan", "algin", "sodium polystyrene sulfonate", "polyurethane-15", "bentonite", "calamine", "ozokerite", "c13-14 isoparaffin", "hydrogenated didecene", "neopentyl glycol diheptanoate", "sodium acetate", "c12-20 alkyl glucoside"], "Texture or film ingredient", "Thickens, stabilizes or gives the product its feel. Rarely causes problems.", [], [], ["COSING"]],
    ["good", ["sodium lauroyl methyl isethionate", "coco-betaine"], "Mild cleansing agent", "A gentle foaming cleanser. Less often linked to allergy than cocamidopropyl betaine, but any cleanser can dry out sensitive skin.", [], [], ["COSING"]],
    ["good", ["hydrolyzed elastin", "soluble collagen", "collagen amino acids", "linoleic acid", "linolenic acid", "elaeis guineensis oil", "hippophae rhamnoides fruit oil"], "Skin-conditioning protein or oil", "Proteins and plant oils that soften and condition. If you are allergic to animal-, fish- or plant-based sources, check the label.", [], ["dryness"], ["COSING"]],
    // Added 1 Oct 2026 after reading hair-care ingredient lists from a Korean store. Written from general cosmetic knowledge, not checked one by one.
    ["mid", ["cetrimonium chloride", "behentrimonium chloride", "behentrimonium methosulfate", "steartrimonium chloride", "stearamidopropyl dimethylamine", "behenamidopropyl dimethylamine"], "Hair conditioning agent, limited by the EU", "A conditioning agent that makes hair soft and easy to comb. The EU limits how much of the quaternary ammonium types can be used. Fine within those limits, but it can irritate the scalp or eyes in strong formulas.", ["irritation"], [], ["EUREG", "COSING"]],
    ["mid", ["climbazole"], "Anti-dandruff ingredient, limited by the EU", "An antifungal for dandruff. The EU allows it only up to a set limit. It can irritate sensitive scalps.", ["irritation"], [], ["EUREG", "COSING"]],
    ["good", ["hydrolyzed silk", "hydrolyzed soy protein", "hydrolyzed keratin", "hydrolyzed rice protein", "hydrolyzed pea protein", "hydrolyzed barley protein", "hydrolyzed lupine protein", "hydrolyzed sweet almond protein", "hydrolyzed corn protein", "hydrolyzed oat protein", "hydrolyzed sesame protein", "hydrolyzed rice bran protein", "triticum vulgare protein", "avena sativa protein extract", "silk amino acids", "keratin amino acids", "elastin amino acids", "keratin", "hydrolyzed honey protein", "silk powder", "oryza sativa seed protein", "oryza sativa bran protein", "prunus amygdalus dulcis protein"], "Protein for hair", "Plant or animal proteins that coat and strengthen hair. If you are allergic to wheat, soy, nuts, sesame or similar, check the label.", [], [], ["COSING"]],
    ["good", ["glutamine", "asparagine", "ornithine", "tryptophan", "taurine", "carnitine", "carnitine hcl", "pyridoxine hcl", "thiamine hcl", "riboflavin", "pantothenic acid", "niacin", "folic acid"], "Amino acid or vitamin", "Building blocks and vitamins used to condition skin and hair.", [], [], ["COSING"]],
    ["good", ["cocamide methyl mea", "cocamide mipa", "cocamide mea", "lauramidopropyl betaine", "sodium lauroyl taurate", "sodium lauroyl methylaminopropionate", "tea-lauroyl methylaminopropionate", "sodium isethionate", "myristyl betaine", "sodium methyl cocoyl taurate", "sodium cocoyl glutamate", "tea-cocoyl glutamate", "disodium cocoamphodiacetate", "decyl glucoside", "coconut acid"], "Cleansing or foam booster", "Gentle cleansing agents and foam boosters used in shampoos and washes.", [], [], ["COSING"]],
    ["good", ["trihydroxystearin", "tetradecene", "hexadecene", "lauryl alcohol", "hydrogenated palm acid", "sodium sulfate", "bambusa vulgaris water", "sea water", "caramel", "acacia senegal gum", "shea butter glycereth-8 esters", "xylitylglucoside", "potassium benzoate", "dodecane", "octadecane", "eicosane", "hexadecane", "pvp", "vp/va copolymer", "maltitol", "anhydroxylitol"], "Texture, solvent or helper ingredient", "Thickens, stabilizes or gives the product its feel. Rarely causes problems.", [], [], ["COSING"]],
    // Added 1 Oct 2026 (second pass over store catalog lists). General knowledge, not checked one by one.
    ["bad", ["zinc pyrithione", "pyrithione zinc"], "Banned in EU cosmetics since 2022", "An anti-dandruff agent. The EU classified it as toxic to reproduction (category 1B) and banned it in cosmetics from 1 March 2022. The EU safety committee itself judged it safe in anti-dandruff shampoo up to 1%, but the ban stayed because other anti-dandruff ingredients exist. It is still sold in other markets, so this is about the strictest rule, not proof of harm at normal use.", ["hormone", "restricted"], [], ["SCCS", "EUREG", "ECHA"]],
    ["mid", ["quaternium-33", "quaternium-87", "quaternium-22", "brassicamidopropyl dimethylamine"], "Hair conditioning agent", "A conditioning agent for hair. Quaternary ammonium types can irritate the scalp or eyes in strong formulas; fine in normal use.", ["irritation"], [], ["COSING"]],
    ["mid", ["lanolin acid"], "Lanolin derivative, can cause allergy", "A wool-fat derivative that softens hair and skin. Lanolin is a known cause of contact allergy for some people.", ["allergy"], [], ["COSING"]],
    ["good", ["honey", "gelatin", "phosphatidylcholine", "hydrogenated phosphatidylcholine", "hydrolyzed milk protein", "milk protein", "whey protein", "hydrolyzed vegetable protein", "hydrolyzed jojoba esters", "hydrolyzed glycosaminoglycans", "soluble proteoglycan", "cystine", "pyridoxine", "beta-carotene", "caffeic acid", "lysine hcl", "sarcosine", "capryloyl glycine", "sodium soy hydrolyzed collagen", "zinc hydrolyzed collagen", "cocodimonium hydroxypropyl hydrolyzed wheat protein", "glycine max polypeptide", "yeast beta-glucan", "biosaccharide gum-4", "saccharide isomerate", "saccharide hydrolysate", "hydroxydecyl ubiquinone"], "Conditioning protein, vitamin or natural extract", "Proteins, vitamins and natural substances that condition skin and hair. If you are allergic to bee products, milk, soy or wheat, check the label.", [], [], ["COSING"]],
    ["good", ["sea salt", "vegetable oil", "dimethyl sulfone", "methyl gluceth-20", "c12-14 pareth-12", "c12-13 pareth-9", "c12-16 alcohols", "t-butyl alcohol", "heptyl undecylenate", "caproic acid", "sodium succinate", "ammonium sulfate", "isopropanolamine", "sodium surfactin", "glyceryl stearates", "myristyl glucoside", "hydrogenated starch hydrolysate", "oleic/linoleic/linolenic polyglycerides", "bis-peg-18 methyl ether dimethyl silane", "peg/ppg-9/2 dimethyl ether", "peg/ppg-14/7 dimethyl ether", "zinc chloride", "juglans regia shell powder", "mineral salts", "ceramide as"], "Texture, solvent or helper ingredient", "Gives the product its feel, cleans, dissolves or stabilizes. Rarely causes problems.", [], [], ["COSING"]],
    // Third pass (Sally hair lists). General knowledge, not checked one by one.
    ["mid", ["quaternium-80", "quaternium-91", "quaternium-95", "dicetyldimonium chloride", "cetrimonium methosulfate", "stearalkonium chloride", "laurdimonium hydroxypropyl hydrolyzed keratin", "c10-40 isoalkylamidopropylethyldimonium ethosulfate"], "Hair conditioning agent", "A conditioning agent for hair. Quaternary ammonium types can irritate the scalp or eyes in strong formulas; fine in normal use.", ["irritation"], [], ["COSING"]],
    ["good", ["phytantriol", "acetic acid", "etidronic acid", "sodium lauryl sulfoacetate", "c11-15 pareth-7", "c12-13 pareth-23", "c12-13 pareth-3", "hydroxypropylammonium gluconate", "hydroxypropylgluconamide", "hydrolyzed vegetable protein pg-propyl silanetriol", "hydrolyzed quinoa", "arginine hcl", "sodium glycolate", "sodium cocoate", "methyl cocoate", "sodium cocoamphoacetate", "sodium phosphate", "fumaric acid", "sodium formate", "sodium starch octenylsuccinate", "hydroxypropyl guar", "ethylhexyl olivate", "butyloctanol", "polyester-37", "avena sativa peptide", "bis-aminopropyl diglycol dimaleate", "palmitoyl myristyl serinate", "sodium methyl 2-sulfolaurate", "dilauryl thiodipropionate"], "Conditioning, cleansing or helper ingredient", "Used to condition hair, adjust pH, stabilize or give the product its feel. Rarely causes problems.", [], [], ["COSING"]],
    // Mexican mass-market lists (Asepxia, Grisi and others). General knowledge, not checked one by one.
    ["mid", ["sulfur"], "Acne ingredient, can dry skin", "A classic ingredient for acne and oily skin. It can dry out or irritate skin, especially combined with other drying acne products.", ["irritation", "drying"], ["acne"], ["COSING"]],
    ["mid", ["sodium palmate", "sodium palm kernelate"], "Soap, can dry skin", "Soap made from palm oil. It cleans well but is alkaline, so it can dry or irritate skin that is dry or sensitive.", ["irritation", "drying"], [], ["COSING"]],
    ["mid", ["tea-sulfate", "tea-lauryl sulfate"], "Strong cleansing agent, can irritate", "A sulfate cleansing agent. Effective, but it can dry or irritate sensitive skin and scalp.", ["irritation", "drying"], [], ["COSING"]],
    ["good", ["ceresin", "zinc sulfate", "sodium lauroyl lactylate", "cetearyl nonanoate", "isopropyl lauroyl sarcosinate", "behenic acid", "caprylic acid", "calcium pantothenate", "citrulline", "mannose", "maltose", "perlite", "silica silylate", "ethoxydiglycol", "trisodium hedta", "zea mays oil", "copernicia cerifera wax", "euphorbia cerifera (candelilla) wax", "cetyl hydroxyethylcellulose", "hydroxypropyl guar hydroxypropyltrimonium chloride", "disodium cocoamphodipropionate", "ceramide 3", "mother of pearl"], "Texture, wax or helper ingredient", "Gives the product its feel, stabilizes or adds shine. Rarely causes problems.", [], [], ["COSING"]],
    // Fourth pass (blog/retailer lists). General knowledge, not checked one by one.
    ["mid", ["quaternium-18", "didecyldimonium chloride", "lauramine oxide", "ammonium chloride"], "Cleansing or conditioning agent, can irritate", "A conditioning or cleansing agent used in hair and body products. It can irritate the scalp, skin or eyes in strong formulas.", ["irritation"], [], ["COSING"]],
    ["good", ["sodium bicarbonate", "sodium carbonate", "zein", "isomalt", "creatine", "dexpanthenol", "polyethylene", "cerebrosides", "ceramide ag", "natto gum", "sodium isostearate", "sodium methyl lauroyl taurate", "c9-11 alkyl glucoside", "isodecyl glyceryl ether", "gamma-docosalactone", "potassium cocoyl hydrolyzed keratin", "hydrolyzed silk pg-propyl methylsilanediol", "hydrolyzed conchiolin protein", "capryloyl salicylic acid"], "Conditioning, cleansing or helper ingredient", "Used to condition, cleanse, buffer or give the product its feel. Rarely causes problems. (Capryloyl salicylic acid is a gentle salicylic-acid cousin; skin that reacts to salicylic acid may react to it.)", [], [], ["COSING"]],
    // Fifth pass (L'Oréal, Kérastase, Revlon, K18 lists). General knowledge, not checked one by one.
    ["mid", ["chlorhexidine digluconate", "chlorhexidine dihydrochloride"], "Antiseptic preservative, limited by the EU", "An antiseptic used as a preservative. The EU allows it only up to a set limit. It can cause contact allergy in some people.", ["allergy", "restricted"], [], ["EUREG", "COSING"]],
    ["mid", ["dipalmitoylethyl hydroxyethylmonium methosulfate", "palmitamidopropyltrimonium chloride"], "Hair conditioning agent", "A conditioning agent for hair. Quaternary ammonium types can irritate the scalp or eyes in strong formulas; fine in normal use.", ["irritation"], [], ["COSING"]],
    ["good", ["2-oleamido-1,3-octadecanediol", "hydroxypropyltrimonium hydrolyzed wheat protein", "sodium cocoyl amino acids", "sodium sarcosinate", "disodium edta-copper", "lauryl alcohol diphosphonic acid", "isostearamide mipa", "safflower glucoside", "honokiol", "magnolol", "caprylic/capric glycerides", "isostearyl neopentanoate", "benzotriazolyl dodecyl p-cresol", "benzophenone-4"], "Conditioning, cleansing or helper ingredient", "Used to condition hair, cleanse gently, protect the formula or give it its feel. Rarely causes problems. If you are allergic to wheat, check the wheat-protein ones.", [], [], ["COSING"]],
    ["mid", ["potassium cocoate"], "Coconut soap, can dry skin", "Soap made from coconut oil. It cleans well but is alkaline, so it can dry or irritate skin that is dry or sensitive.", ["irritation", "drying"], [], ["COSING"]],
    // Sixth pass (toothpaste, mouthwash and Natura lists). General knowledge, not checked one by one.
    ["mid", ["sodium fluoride", "sodium monofluorophosphate", "stannous fluoride", "olaflur", "amine fluoride"], "Fluoride for teeth, limited by the EU", "Fluoride strengthens enamel and is the main active in most toothpastes. The EU limits it to 0.15% fluoride in toothpaste. Swallowing toothpaste regularly, especially in children under 6, can cause white spots on teeth (dental fluorosis), so use a pea-sized amount for children.", ["restricted"], [], ["SCCS", "EUREG"]],
    ["mid", ["cetylpyridinium chloride"], "Antibacterial for mouthwash, limited by the EU", "An antibacterial used in mouthwash and some toothpastes. The EU limits how much is allowed. It can stain teeth with long use and irritate the mouth in some people.", ["irritation", "restricted"], [], ["EUREG", "COSING"]],
    ["mid", ["flavor", "flavour", "flavouring", "natural flavor", "natural flavors", "natural flavour", "flavoring", "peppermint oil and other natural flavor"], "Flavoring, can contain allergens", "A flavoring blend (mint, spice). It does not list what is inside. The EU requires the main fragrance allergens to be named when they are present above a set level, so if you are sensitive to flavors or fragrance, check the package.", ["allergy", "irritation"], [], ["EUREG", "COSING"]],
    ["mid", ["eucalyptol", "thymol", "eugenia caryophyllus oil", "eugenia caryophyllus (clove) bud oil", "conobea scoparioides leaf oil"], "Essential-oil flavor or antiseptic, can irritate", "A plant-derived flavor or antiseptic used in mouthwash and mint products. It can irritate the mouth, gums or skin in some people, especially at higher strengths.", ["irritation", "allergy"], [], ["COSING"]],
    ["mid", ["tbhq", "tert-butylhydroquinone", "sodium palmitate", "sodium stearate", "sodium oleate", "sodium laurate", "sodium myristate", "sodium caprylate", "sodium caprate", "sodium linoleate", "sodium arachidate"], "Preservative or soap salt, mild", "Antioxidant or fatty-acid soap used in small amounts. Soap salts are alkaline and can dry skin; the antioxidant TBHQ can cause contact allergy in a few people.", ["irritation"], [], ["COSING"]],
    ["good", ["sodium saccharin", "saccharin", "sucralose", "rebaudioside a", "steviol glycosides", "stevia rebaudiana leaf extract"], "Sweetener", "Sweetener used in toothpaste and mouthwash so they taste pleasant without sugar. Well tolerated.", [], [], ["COSING"]],
    ["good", ["calcium carbonate", "calcium pyrophosphate", "dicalcium phosphate"], "Gentle polishing abrasive", "A fine mineral that polishes away stains and plaque from teeth.", [], [], ["COSING"]],
    ["good", ["sodium hexametaphosphate", "trisodium phosphate", "pentasodium triphosphate", "tetrasodium pyrophosphate", "disodium pyrophosphate", "diammonium phosphate", "phosphoric acid", "hydrochloric acid", "potassium citrate", "malonic acid"], "Tartar control or pH adjuster", "Used to slow tartar build-up, stabilize the formula or adjust the pH. Well tolerated in the amounts used.", [], [], ["COSING"]],
    ["good", ["zinc lactate", "zinc citrate", "stannous chloride", "potassium nitrate", "arginine bicarbonate"], "Mouth-care active", "Zinc and stannous salts help against plaque and bad breath. Potassium nitrate and arginine ease tooth sensitivity. Stannous salts can leave a mild surface stain on teeth with long use.", [], [], ["COSING"]],
    ["good", ["ci 74160", "ci 73360", "ci 74260", "ci 42051", "ci 77288", "red 33", "yellow 10", "pigment blue 15", "pigment green 7"], "Colorant", "A colorant that gives the product its color. Permitted in cosmetics. Some can stain or cause rare contact allergy.", [], [], ["EUREG", "COSING"]],
    ["good", ["oenocarpus bataua fruit oil", "olus oil", "hydrogenated farnesene", "myristyl theobroma grandiflorum seedate", "propylene glycol diheptanoate", "glyceryl dibehenate", "tristearin"], "Emollient or oil", "Plant-based or synthetic oil or wax that softens and conditions. Usually well tolerated.", [], ["dryness"], ["COSING"]],
    ["good", ["polyurethane-14", "polyacrylic acid", "methacrylic acid", "disodium phenyl dibenzimidazole tetrasulfonate"], "Film former or UV filter", "A polymer that forms a light film on skin or hair, or a UV filter. Well tolerated in the amounts used.", [], [], ["COSING"]],
    ["mid", ["sodium chlorite", "papain", "natural mint flavor", "natural mint flavour"], "Oral-care active or flavor, can irritate", "Sodium chlorite is an oxidizing agent used in mouthwash to neutralize odor-causing compounds. Papain is an enzyme that can cause allergy in sensitive people. Natural flavors do not list what is inside. All can irritate the mouth in some people.", ["irritation", "allergy"], [], ["COSING"]],
    ["good", ["lysozyme", "amylase", "amyloglucosidase", "serralysin", "lactoferrin", "glucose oxidase", "tetrapotassium pyrophosphate", "polyvinylpyrrolidone", "pvp"], "Enzyme or tartar-control ingredient", "Enzymes and proteins found naturally in saliva or milk, and mineral salts that slow tartar. Well tolerated in the amounts used.", [], [], ["COSING"]],
    // Seventh pass (Kundal and anillO lists from the OnSkin recordings, 6 Oct 2026). General knowledge, not checked one by one.
    ["good", ["peat water", "onsen-sui", "carob", "camellia", "soymilk", "illite", "sand", "acorus calamus", "calendula officinalis flower oil", "euterpe oleracea fruit oil", "oryza sativa (rice) powder", "oryza sativa powder", "cucurbita pepo (pumpkin) powder", "citrus limon peel powder", "amber powder", "carthamus tinctorius flower", "prunus persica fruit", "simmondsia", "macadamia ternifolia", "macadamia ternifolia fruit oil", "pelargonium graveolens water", "helianthus annuus seed oil unsaponifiables", "moringa oil/hydrogenated moringa oil esters", "almond oil/polyglyceryl-10 esters", "hydrogenated olive oil lauryl esters", "lactobacillus extracellular vesicles", "lactobacillus ferment lysate filtrate", "glaucine", "oleanolic acid"], "Plant-derived ingredient", "A plant extract, water, powder or oil used to soften, soothe or add texture. Mostly low-risk, but plant ingredients can cause rare allergies. Rated as a group, not individually.", [], [], ["COSING"]],
    ["good", ["hexapeptide 9", "hexapeptide-9", "nonapeptide 1", "dipeptide 4", "acetyl tripeptide 1", "copper tripeptide 1", "acetyl octapeptide 3", "acetyl tetrapeptide 2", "palmitoyl tripeptide 5", "dipeptide diaminobutyroyl benzylamide diacetate", "pisum sativum peptide", "pisum sativum (pea) peptide", "hydrolyzed extensin", "hydrolyzed hazelnut protein", "hydrolyzed sodium", "coco-glucoside sodium lauroyl oat amino acids"], "Peptide or protein", "Short chains of amino acids or plant proteins used to condition hair or support skin. Generally well tolerated.", [], [], ["COSING"]],
    ["good", ["hydrogenated poly (c6-14 olefin)", "tetradecane", "caprylic/capric glyceride", "hydroxypropyl methylcellulose stearoxy ether", "ceramide eos", "ceramides", "sodium sulfite", "sodium naphthalenesulfonate", "denatonium benzoate", "raspberry ketone", "ci 77220", "ci 45380", "edta"], "Texture, colorant or support ingredient", "Used for texture, color or to keep the formula stable. Permitted in cosmetics and well tolerated in the amounts used.", [], [], ["COSING"]],
    ["good", ["c12-14 sec-pareth-7", "trideceth 8", "trideceth 12", "c12-14 alketh-12", "c12-13 alketh-9"], "Emulsifier or solubilizer (rated by type)", "Helps oil and water mix. Rated by type, not individually. Considered safe when manufacturers keep impurities such as 1,4-dioxane low.", [], [], ["COSING"]],
    ["mid", ["dipalmitoylethyl dimonium chloride", "quaternium-52"], "Hair conditioning agent", "A conditioning agent for hair. Quaternary ammonium types can irritate the scalp or eyes in strong formulas; fine in normal use.", ["irritation"], [], ["COSING"]],
    ["mid", ["lauramide dea"], "Foam booster, can carry nitrosamine impurities", "A foam booster related to cocamide DEA. DEA compounds can form nitrosamines, which is why some regulators ask makers to limit them.", ["irritation"], [], ["COSING"]],
    ["mid", ["cymbopogon nardus oil", "cymbopogon nardus (citronellal) oil", "piper nigrum (black pepper) fruit oil", "myristica fragrans aril oil", "pogostemon cablin leaf oil", "citrus nobilis (mandarin orange) oil", "citrus aurantium amara (bitter orange)", "acorus calamus root oil", "rose flower oil"], "Essential oil, can irritate or sensitize", "A plant essential oil used for scent. Essential oils contain fragrance compounds that can irritate or cause allergy in sensitive skin and scalp. Not individually checked.", ["irritation", "allergy"], [], ["COSING"]],
    ["mid", ["magnesium laureth sulfate", "sodium laureth-8 sulfate", "magnesium laureth-8 sulfate", "sodium oleth sulfate", "magnesium oleth sulfate"], "Cleansing agent, can dry the skin", "Foaming cleanser of the laureth sulfate family. Milder than SLS but can still dry or irritate sensitive skin, so a gentle wash for delicate areas is often better without it.", ["irritation", "dryness"], [], ["COSING"]],
    ["mid", ["dimethyl stearamine", "octoxynol-12", "formic acid", "dichlorobenzyl alcohol"], "Can irritate in strong formulas", "A conditioning, solubilizing or preserving ingredient that is fine at normal levels but can irritate sensitive skin in stronger products.", ["irritation"], [], ["COSING"]],
    ["mid", ["lavandula hybrida oil", "aniba rosodora wood oil", "mentha spicata herb oil", "citrus aurantium amara leaf/twig oil", "tagetes minuta flower oil", "vetiveria zizanoides root oil", "2-methyl 5-cyclohexylpentanol", "citrus paradisi (grapefruit) peel oil", "cupressus sempervirens leaf/nut/stem oil", "amyris balsamifera bark oil", "zingiber officinale (ginger) root oil", "citrus tangerina (tangerine) peel oil", "citrus nobilis (mandarin orange) peel oil", "artemisia herba-alba oil", "methyl diisopropyl propionamide"], "Fragrance or essential oil, can sensitize", "A scent ingredient or plant essential oil. Some people react to fragrance, especially on delicate skin.", ["allergy"], [], ["COSING"], "fragrance"],
    ["good", ["sodium lauroyl isethionate", "sodium methyl oleoyl taurate", "sodium sweetalmondamphoacetate", "stearamine oxide", "sodium lauryl glucose carboxylate", "disodium capryloamphodiacetate", "cocamidopropyl pg-dimonium chloride phosphate", "c12-15 pareth-3", "c12-15 pareth-3 phosphate"], "Mild cleansing or emulsifying agent", "A mild surfactant or emulsifier that helps a wash foam or a formula stay mixed. Generally gentle at normal levels.", [], [], ["COSING"]],
    ["good", ["alpha-glucan oligosaccharide", "lactose", "lactis proteinum", "maris sal", "apple cider vinegar", "vinegar", "cocos nucifera water", "tamarindus indica seed polysaccharide", "nicotinamide mononucleotide", "aloe barbadensis (aloe vera) gel", "chamomilla recutita (matricaria) flower oil"], "Soothing, prebiotic or conditioning ingredient", "A gentle plant, sugar or milk-derived ingredient used to soothe or condition. Well tolerated by most people.", [], [], ["COSING"]],
    ["good", ["cetearyl isononanoate", "cocoglycerides", "triisostearin", "polyisoprene", "hydroxyethyl ethylcellulose", "sodium alginate sulfate", "hydrogenated vegetable glycerides citrate", "phenethyl alcohol", "phenylpropanol", "glycerol formal", "ci 14720", "hippophae rhamnoides water", "ethyl ascorbyl ether", "hydrogenated poly(c6-20 olefin)", "butyl avocadate", "oryza sativa (rice) bran water", "amylodextrin", "citrus aurantium bergamia (bergamot) peel water", "aloe vera gel", "ci 16255", "synthetic beeswax", "quercetin", "kaempferol", "mannan", "polydextrose", "amylopectin", "diethyllutidinate", "diaminopyrimidine oxide", "c11-13 isoalkane", "c11-15-isoalkanes", "c11-13 isoparaffin", "maleic acid", "piperine", "ethane", "xylene sulfonic acid", "ci 45100", "hc blue no. 2", "hc blue no. 15", "magnesium acetate", "amino acids", "centella asiatica", "polycaprolactone", "hydroxypalmitoyl sphinganine", "sclerotium gum", "aminopropyl triethoxysilane", "starch acetate", "distearyl ether", "rose ketones", "citrus aurantium flower oil", "montmorillonite", "glycyrrhetinic acid", "hydroxyethylpiperazine ethane sulfonic acid", "hydrogenated coconut acid", "hydroxypropyltrimonium lemon protein", "oryza sativa starch", "ci 61565", "ci 61565 / green 6", "phenylethyl resorcinol", "2-oleamido-1,3-octadecanediol", "isobutylamido thiazolyl resorcinol", "sodium lauroamphoacetate", "hydrogenated vegetable oil", "oryza sativa cera", "oryza sativa bran wax", "ceramide", "ceramide 1", "ceramide 6", "ceramide 6 ii", "peg/ppg/polybutylene glycol-8/5/3 glycerin", "nylon-12", "fish oil", "sodium thiosulfate", "methoxypropylamino cyclohexenylidene ethoxyethylcyanoacetate", "isoquercitrin", "glucosylrutin", "tributyl citrate", "undecane", "tridecane", "pectin", "red 30 lake", "potato starch modified", "c12-13 alkyl lactate", "triacetin", "glucamine", "glucuronic acid", "oxothiazolidinecarboxylic acid", "dodecene", "dicocoylethyl hydroxyethylmonium methosulfate", "sodium carbomer", "polyglycerin-10", "escin", "ethylhexyl benzoate", "dicetyl phosphate", "sodium propoxyhydroxypropyl thiosulfate silica", "octyldecanol", "phenethyl benzoate", "gardenia taitensis flower", "whey", "lac", "ketoglutaric acid", "magnesium stearate", "zinc ricinoleate", "tetrahydroxypropyl ethylenediamine", "c9-12 alkane", "c13-14 alkane", "glyceryl undecylenate"], "Texture, preservative or support ingredient", "Used for texture, color or to keep the formula stable. Permitted and considered low risk at normal levels.", [], [], ["COSING"]],
    ["mid", ["myrtrimonium bromide", "polyaminopropyl biguanide", "benzethonium chloride", "menthoxypropanediol", "methyl benzoate", "ethanolamine", "sodium polynaphthalenesulfonate", "sodium dodecylbenzenesulfonate"], "Preservative, pH adjuster or cooling agent, can irritate", "A preservative, pH adjuster, cooling agent or cleansing ingredient that is permitted at normal levels but can irritate sensitive skin, eyes or the mouth in stronger products.", ["irritation"], [], ["COSING"]],
    // Added 7 Oct 2026 (found in a Euphoria Mexico sunscreen list). It is in Annex II of the EU cosmetics regulation (the consolidated copy in tools/data lists it). Nobody has reviewed this entry.
    ["bad", ["4-methylbenzylidene camphor", "4-mbc", "3-(4'-methylbenzylidene) camphor"], "Banned in EU cosmetics", "A chemical UV filter (also called 4-MBC) that the EU has put on its list of substances banned in cosmetics because of concerns about hormone-like activity. Sunscreens made for other markets can still contain it.", ["hormone", "restricted"], [], ["EUREG", "SCCS"]],
    // Added 8 Oct 2026 (Versed and Fenty Beauty lists read from OnSkin). General knowledge; none of these is banned or restricted in the EU cosmetics regulation as far as we know, and the strictest regulator would win. Nobody has reviewed these entries.
    ["good", ["helianthus annuus (sunflower) seed wax", "stearyl behenate", "calcium sodium borosilicate", "caprylic/capric/myristic/stearic triglyceride", "dipentaerythrityl hexa c5-9 acid esters", "glyceryl oleate citrate", "triheptanoin", "magnesium myristate", "stearoyl glutamic acid", "zinc stearate", "caesalpinia spinosa gum", "hydrogenated ethylhexyl olivate", "dibutyl lauroyl glutamide", "dibutyl ethylhexanoyl glutamide", "butyrospermum parkii (shea) butter unsaponifiables", "hydrogenated polycyclopentadiene", "tricaprylin", "hydroxystearic/linolenic/oleic polyglycerides", "acacia decurrens flower wax", "sucrose acetate isobutyrate", "isodecyl neopentanoate", "c18-21 alkane", "c15-19 alkane", "pentaerythrityl adipate/caprate/caprylate/heptanoate", "sodium stearoyl lactylate", "quaternium-90 bentonite", "diamond powder", "shea butter ethyl esters", "aloe barbadensis leaf", "sodium dilauramidoglutamide lysine", "astrocaryum tucuma seed butter", "polyglyceryl-10 dipalmitate", "euphorbia cerifera (candelilla) wax(candelilla cera/cire de candelilla)", "cera carnauba/copernicia cerifera (carnauba) wax/cire de carnauba", "pumice"], "Emollient, wax, ester or texture agent (rated by type)", "Gives slip, body or a smooth feel to creams, sticks and powders. Rated by type, not individually. Generally well tolerated.", [], [], ["COSING"]],
    ["good", ["dimethyl isosorbide", "cocos nucifera (coconut) liquid endosperm", "12 hexanediol", "coenzyme a", "ethyl ferulate", "phloretin", "hesperidin methyl chalcone", "3-glyceryl ascorbate", "meadowfoam delta-lactone", "methyl dihydroabietate", "sodium anisate", "sodium benzotriazolyl butylphenol sulfonate"], "Solvent, antioxidant, skin-conditioning or stabilizing ingredient", "Used as a solvent, an antioxidant, a skin-conditioning agent or to keep the formula stable. Generally well tolerated at normal levels.", [], [], ["COSING"]],
    ["good", ["manganese violet (ci 77742)", "ultramarines (ci 77007)", "red 28 lake (ci 45410)", "iron oxide (ci 77491,ci 77492,ci 77499)", "chlorophyll", "red 7 (ci 15850)", "carmine (ci 75470)", "blue 1 lake (ci 42090)"], "Colorant", "A colorant that gives the product its color. Permitted in cosmetics; some are limited to certain product types (for example not near the eyes).", [], [], ["COSING"]],
    ["mid", ["chamaecyparis obtusa oil"], "Plant essential oil, can sensitize", "A scented plant oil. Essential oils can irritate or sensitize some skin in leave-on products.", ["irritation"], [], ["COSING"]],
  ];

  var INDEX = {};
  RAW.forEach(function (r) {
    var entry = {
      level: r[0], family: r[7] || null, note: r[2], detail: r[3], risks: r[4], helps: r[5],
      // "danger" = the entry says the EU bans it in cosmetics, or it is marked as one (9th field, e.g. carbon black).
      // Only used by the score (see analyze).
      danger: r[0] === "bad" && (r[8] === true || /^(banned|not allowed|mercury, banned)/i.test(r[2])),
      src: r[6].map(function (k) { return SOURCES[k]; }).sort(function (a, b) { return a.rank - b.rank; })
    };
    r[1].forEach(function (name) { INDEX[name] = entry; });
  });

  // Spelling variants copied from source lists (typos or spacing): rated like the proper name.
  [
    [["ethylhexyglycerin", "ethyl hexyl glycerin", "ethylhexyl-glycerin", "ethylhexyl glycerin"], "ethylhexylglycerin"],
    [["polyquarternium-10"], "polyquaternium-10"],
    [["caprylic capric triglyceride", "caprylic capric/triglyceride", "caprylic/capric triglycerides"], "caprylic/capric triglyceride"],
    [["1,2 hexanediol", "1 2 hexanediol", "1.2-hexanediol", "2-hexanediol"], "1,2-hexanediol"],
    [["eucalyptus globulous leaf oil"], "eucalyptus globulus leaf oil"]
  ].forEach(function (a) { a[0].forEach(function (n) { if (!INDEX[n] && INDEX[a[1]]) INDEX[n] = INDEX[a[1]]; }); });

  function clean(s) {
    return s.toLowerCase().replace(/[*†‡]/g, "").replace(/\s+/g, " ").trim();
  }

  // Split on commas that are not inside parentheses.
  function split(text) {
    var out = [], depth = 0, cur = "";
    text = text.replace(/^\s*(ingredients?|ingredientes|ingr\u00e9dients|inci)\s*:?\s*/i, "").replace(/[.;]\s*$/, "");
    for (var i = 0; i < text.length; i++) {
      var c = text[i];
      if (c === "(") depth++;
      if (c === ")") depth = Math.max(0, depth - 1);
      var inNumber = c === "," && /\d/.test(text[i - 1] || "") && /\d/.test(text[i + 1] || "");
      if ((c === "," || c === ";") && depth === 0 && !inNumber) { out.push(cur); cur = ""; } else { cur += c; }
    }
    out.push(cur);
    return out.map(function (s) { return s.trim(); }).filter(Boolean);
  }

  // Types of ingredient that are rated as a group instead of one by one (K-beauty formulas are full of them).
  // Checked only when the exact name is not in the list above.
  function typeEntry(level, note, detail, src) {
    return { level: level, note: note, detail: detail, risks: [], helps: [], src: src.map(function (k) { return SOURCES[k]; }) };
  }
  var PEPTIDE = typeEntry("good", "Peptide (rated by type)", "Short chains of amino acids used in anti-aging and firming products. Rated by type, not individually. Generally well tolerated.", ["COSING"]);
  var SILICONE = typeEntry("good", "Silicone (rated by type)", "Silicones smooth skin and make products glide. Rated by type, not individually. Most are considered safe in cosmetics.", ["COSING"]);
  var ETHOXY = typeEntry("good", "Emulsifier or solubilizer (rated by type)", "Helps oil and water mix. Rated by type, not individually. Considered safe when manufacturers keep impurities such as 1,4-dioxane low.", ["COSING"]);
  var POLYMER = typeEntry("good", "Texture polymer (rated by type)", "Thickens or stabilizes the formula. Rated by type, not individually. Generally well tolerated.", ["COSING"]);
  var ESTER = typeEntry("good", "Emollient ester (rated by type)", "Softens skin and improves the feel of a product. Rated by type, not individually. Generally well tolerated.", ["COSING"]);
  var PLANT = typeEntry("good", "Plant extract or ferment (rated by type)", "A botanical extract or ferment used to soothe, hydrate or protect. Rated by type, not individually: most are low-risk, but any plant can cause an allergy in some people.", ["COSING"]);
  var PLANT_OIL = typeEntry("good", "Plant oil or butter (rated by type)", "A carrier oil or butter that softens skin. Rated by type, not individually. Nut and seed oils matter if you have that allergy.", ["COSING"]);
  var PATTERNS = [
    [/peptide-\d+/, PEPTIDE],
    [/(methicone|siloxane|silsesquioxane|dimethicone|silicone|silanol)/, SILICONE, /cyclo/],
    [/^(peg|ppg)[-\/ ]?\d|^[a-z]+eth-\d+|^polysorbate|^poloxamer|^polyglyceryl-\d+/, ETHOXY],
    [/(acrylate|acrylamide|acryloyldimethyl|copolymer|crosspolymer|^polyquaternium)/, POLYMER],
    [/(seed|kernel|nut|germ) oil$|butter$/, PLANT_OIL],
    [/(extract|ferment filtrate|ferment lysate|ferment|juice|protoplasts)$|(leaf|flower|root|fruit|bark|seed|stem|bulb|rhizome|sprout|shoot) (water|powder)$/, PLANT],
    [/(ethylhexanoate|isostearate|laurate|myristate|palmitate|stearate|oleate|dilinoleate|caprate|caprylate|adipate|sebacate|succinate|malate|trimellitate|glutamate)$/, ESTER, /^(sodium|potassium|calcium|magnesium|zinc|ammonium|aluminum)/]
  ];

  // Spanish names printed on Mexican labels -> the INCI name the ratings use. The product keeps the Spanish text exactly as on the package;
  // this table only lets the app recognise and rate it. Keys have no accents. Added 7 Oct 2026 (OH! GANICS); extend it when a new Spanish label needs it.
  var ES_ALIAS = {
    "agua": "aqua", "agua desionizada": "aqua", "agua purificada": "aqua", "glicerina": "glycerin", "fragancia": "fragrance (parfum)", "perfume": "fragrance (parfum)", "aroma": "fragrance (parfum)",
    "laurel sulfosuccinato disodico": "disodium laureth sulfosuccinate", "lauret sulfosuccinato disodico": "disodium laureth sulfosuccinate", "proteina de trigo": "hydrolyzed wheat protein", "proteina de trigo hidrolizada": "hydrolyzed wheat protein", "cocamidopropil betaina": "cocamidopropyl betaine", "monoetanolamida de acidos grasos de coco": "cocamide mea",
    "decil glucosido": "decyl glucoside", "coco glucosido": "coco-glucoside", "cocoanfoacetato de sodio": "sodium cocoamphoacetate", "policuaternio-7": "polyquaternium-7", "policuaternio-10": "polyquaternium-10",
    "peg-12 dimeticona": "peg-12 dimethicone", "dimeticona": "dimethicone", "jugo de hoja de aloe": "aloe barbadensis leaf juice", "extracto de alga": "fucus vesiculosus extract",
    "magnesio pca": "magnesium pca", "zinc pca": "zinc pca", "manganeso pca": "manganese pca", "calcio pca": "calcium pca", "queratina hidrolizada": "hydrolyzed keratin", "succinimida de chitosan": "chitosan succinamide",
    "extracto de flor de manzanilla": "chamomilla recutita (matricaria) flower extract", "extracto de flor de calendula": "calendula officinalis flower extract",
    "alcohol bencilico": "benzyl alcohol", "caprilato de glicerilo": "glyceryl caprylate", "undecilenato de glicerilo": "glyceryl undecylenate", "acido citrico": "citric acid", "edta disodico": "disodium edta",
    "fenoxietanol": "phenoxyethanol", "propilenglicol": "propylene glycol", "butilenglicol": "butylene glycol", "sorbato de potasio": "potassium sorbate", "benzoato de sodio": "sodium benzoate", "acido benzoico": "benzoic acid", "acido sorbico": "sorbic acid",
    "acido salicilico": "salicylic acid", "acido hialuronico": "hyaluronic acid", "acido lactico": "lactic acid", "acido glicolico": "glycolic acid", "acido estearico": "stearic acid", "pantenol": "panthenol", "niacinamida": "niacinamide",
    "alcohol cetilico": "cetyl alcohol", "alcohol cetearilico": "cetearyl alcohol", "alcohol estearilico": "stearyl alcohol", "cloruro de sodio": "sodium chloride", "hidroxido de sodio": "sodium hydroxide",
    "laurilsulfato de sodio": "sodium lauryl sulfate", "lauril sulfato de sodio": "sodium lauryl sulfate", "lauret sulfato de sodio": "sodium laureth sulfate", "laureth sulfato de sodio": "sodium laureth sulfate",
    "aceite mineral": "paraffinum liquidum", "vaselina": "petrolatum", "petrolato": "petrolatum", "lanolina": "lanolin", "cera de abejas": "cera alba", "trietanolamina": "triethanolamine", "urea": "urea",
    "tocoferol": "tocopherol", "acetato de tocoferol": "tocopheryl acetate", "oxido de zinc": "zinc oxide", "dioxido de titanio": "titanium dioxide", "carbomero": "carbomer", "metilparabeno": "methylparaben", "propilparabeno": "propylparaben",
    "metilisotiazolinona": "methylisothiazolinone", "metilcloroisotiazolinona": "methylchloroisothiazolinone", "formaldehido": "formaldehyde", "limoneno": "limonene", "linalool": "linalool", "geraniol": "geraniol", "citronelol": "citronellol",
    // Added 7 Oct 2026 (Euphoria Mexico lists, Spanish translation of the INCI name). General knowledge; the strictest regulator wins; nobody has reviewed them.
    "1,2-hexanodiol": "1,2-hexanediol", "dipropilenglicol": "dipropylene glycol", "propanodiol": "propanediol", "pentilenglicol": "pentylene glycol", "metilpropanodiol": "methylpropanediol", "hidroxiacetofenona": "hydroxyacetophenone",
    "caprililglicol": "caprylyl glycol", "etilhexilglicerina": "ethylhexylglycerin", "betaina": "betaine", "alantoina": "allantoin", "adenosina": "adenosine", "trehalosa": "trehalose", "glucosa": "glucose", "xilitol": "xylitol", "eritritol": "erythritol",
    "arginina": "arginine", "biotina": "biotin", "ectoina": "ectoin", "manitol": "mannitol", "lecitina": "lecithin", "lecitina hidrogenada": "hydrogenated lecithin", "caolin": "kaolin", "dextrina": "dextrin", "silice": "silica", "escualano": "squalane",
    "hidroxietil urea": "hydroxyethyl urea", "trometamina": "tromethamine", "goma xantana": "xanthan gum", "goma de celulosa": "cellulose gum", "celulosa microcristalina": "microcrystalline cellulose", "carbomero sodico": "sodium carbomer",
    "hialuronato de sodio": "sodium hyaluronate", "acido hialuronico sodico": "sodium hyaluronate", "acido hialuronico hidrolizado": "hydrolyzed hyaluronic acid", "colageno hidrolizado": "hydrolyzed collagen", "acido ascorbico": "ascorbic acid",
    "acido deshidroacetico": "dehydroacetic acid", "acido dehidroacetico": "dehydroacetic acid", "citrato sodico": "sodium citrate", "citrato de sodio": "sodium citrate", "acetato de tocoferilo": "tocopheryl acetate", "esponja hidrolizada": "hydrolyzed sponge",
    "gliceret-26": "glycereth-26", "metil gluceth-20": "methyl gluceth-20", "polisorbato 20": "polysorbate 20", "polisorbato 80": "polysorbate 80", "poliglicerina-3": "polyglycerin-3", "laurato de poliglicerilo-10": "polyglyceryl-10 laurate",
    "estearato de poliglicerilo-6": "polyglyceryl-6 stearate", "caprato de poliglicerilo-4": "polyglyceryl-4 caprate", "miristato de poliglicerilo-10": "polyglyceryl-10 myristate", "olivato de cetearilo": "cetearyl olivate", "olivato de sorbitan": "sorbitan olivate",
    "estearato de sorbitan": "sorbitan stearate", "estearato de glicerilo": "glyceryl stearate", "palmitato de cetilo": "cetyl palmitate", "etilhexanoato de cetilo": "cetyl ethylhexanoate", "carbonato de dicaprililo": "dicaprylyl carbonate",
    "trietilhexanoina": "triethylhexanoin", "triglicerido caprilico/cáprico": "caprylic/capric triglyceride", "triglicerido caprilico/caprico": "caprylic/capric triglyceride", "isononanoato de isononilo": "isononyl isononanoate", "isononil isononanoato": "isononyl isononanoate",
    "adipato de dibutilo": "dibutyl adipate", "salicilato de butiloctilo": "butyloctyl salicylate", "benzoato de alquilo c12-15": "c12-15 alkyl benzoate", "benzoato de fenetilo": "phenethyl benzoate", "octildodecanol": "octyldodecanol", "laurato de isoamilo": "isoamyl laurate",
    "ciclohexasiloxano": "cyclohexasiloxane", "caprilil meticona": "caprylyl methicone", "vinil dimeticona": "vinyl dimethicone", "polimetilsilsesquioxano": "polymethylsilsesquioxane", "sililato de silice": "silica silylate", "polietileno": "polyethylene", "ceresina": "ceresin",
    "tripropilenglicol": "tripropylene glycol", "alcohol desnaturalizado": "alcohol denat.", "alcohol": "alcohol", "cera de abeja": "cera alba", "cera de carnauba": "copernicia cerifera (carnauba) wax", "aceite de ricino": "ricinus communis (castor) seed oil",
    "lauril glucosido": "lauryl glucoside", "cocoanfodiacetato disodico": "disodium cocoamphodiacetate", "cocoil glicinato de potasio": "potassium cocoyl glycinate", "lauramida dea": "lauramide dea", "copolimero de acrilatos": "acrylates copolymer",
    "copolimero peg/ppg-17/6": "peg/ppg-17/6 copolymer", "copolimero de acriloildimetiltaurato de amonio/vp": "ammonium acryloyldimethyltaurate/vp copolymer", "copolimero de acrilodimetiltaurato de amonio/vp": "ammonium acryloyldimethyltaurate/vp copolymer",
    "polimero cruzado de acrilatos/acrilato de alquilo c10-30": "acrylates/c10-30 alkyl acrylate crosspolymer", "sulfato de calcio": "calcium sulfate", "oxido de magnesio": "magnesium oxide", "pirofosfato tetrasodico": "tetrasodium pyrophosphate",
    "fenoxietanol": "phenoxyethanol", "etilhexilglicerina": "ethylhexylglycerin", "pantenol": "panthenol", "acido hialuronico": "hyaluronic acid", "acido azelaico": "azelaic acid", "retinol": "retinol", "retinal": "retinal", "niacinamida": "niacinamide",
    "tocoferol": "tocopherol", "vitamina e": "tocopherol", "acido ferulico": "ferulic acid", "acido tranexamico": "tranexamic acid", "acido ascorbico": "ascorbic acid", "glutation": "glutathione", "ceramida np": "ceramide np", "ceramida ap": "ceramide ap", "ceramida eop": "ceramide eop"
  };
  // Spanish botanical names ("extracto de hoja de X", "aceite de semilla de X", "manteca de X", "agua de flor de X"): rewritten to the English INCI form so the plant/oil type rules in PATTERNS rate them.
  var ES_PART = { hoja: "leaf", raiz: "root", flor: "flower", fruto: "fruit", semilla: "seed", tallo: "stem", corteza: "bark", cascara: "peel", rizoma: "rhizome", callo: "callus", "hoja/tallo": "leaf/stem" };
  function esGeneric(raw) {
    var n = deacc(clean(raw.replace(/\([^)]*\)/g, " "))).replace(/\s+/g, " ").trim();
    var m = n.match(/^(extracto|aceite|manteca|agua|jugo|polvo) (?:hidrolizado )?de (?:(hoja\/tallo|hoja|raiz|flor|fruto|semilla|tallo|corteza|cascara|rizoma|callo|cultivo de callo) (?:de |del )?)?([a-z][a-z .\-]+)$/);
    if (!m || /colageno|proteina|levadura|leche|perla|alga$/.test(m[3]) && m[1] === "extracto" && /colageno/.test(m[3])) return null;
    var part = m[2] ? (ES_PART[m[2]] || "") : "", sp = m[3].trim();
    if (m[1] === "extracto") return sp + (part ? " " + part : "") + " extract";
    if (m[1] === "aceite") return sp + (part ? " " + part : "") + " oil";
    if (m[1] === "manteca") return sp + " butter";
    if (m[1] === "agua") return sp + (part ? " " + part : "") + " water";
    if (m[1] === "jugo") return sp + (part ? " " + part : "") + " juice";
    return sp + (part ? " " + part : "") + " powder";
  }
  function esName(raw) { var full = clean(raw), noParen = clean(raw.replace(/\([^)]*\)/g, " ")); return ES_ALIAS[deacc(full)] || ES_ALIAS[deacc(noParen)] || esGeneric(raw); }
  function deacc(s) { return s.normalize("NFD").replace(/[\u0300-\u036f]/g, ""); }

  // Try the full name, then the name without parentheses, then each parenthetical, then tidied-up spellings
  // (OCR often leaves "peg - 100" or splits a word), then each part of "a / b", then the type rules.
  function lookup(raw) {
    var full = clean(raw);
    if (INDEX[full]) return INDEX[full];
    var noParen = clean(raw.replace(/\([^)]*\)/g, " "));
    if (INDEX[noParen]) return INDEX[noParen];
    var es = esName(raw);
    if (es) return lookup(es);
    var inside = raw.match(/\(([^)]*)\)/g) || [];
    for (var i = 0; i < inside.length; i++) {
      var p = clean(inside[i].slice(1, -1));
      if (INDEX[p]) return INDEX[p];
    }
    var tidy = [noParen.replace(/\s*-\s*/g, "-"), noParen.replace(/\s+-\s+/g, ""), noParen.replace(/\s*\/\s*/g, "/")];
    for (var t = 0; t < tidy.length; t++) if (INDEX[tidy[t]]) return INDEX[tidy[t]];
    if (/\//.test(noParen)) {
      var parts = noParen.split("/");
      for (var q = 0; q < parts.length; q++) { var part = parts[q].trim(); if (INDEX[part]) return INDEX[part]; }
    }
    if (/hyaluron/.test(noParen)) return INDEX["hyaluronic acid"];
    var name = tidy[0];
    for (var k = 0; k < PATTERNS.length; k++) {
      if (PATTERNS[k][0].test(name) && !(PATTERNS[k][2] && PATTERNS[k][2].test(name))) return PATTERNS[k][1];
    }
    return null;
  }

  // Score (new model, 4 Oct 2026). Each ingredient has a tier for the score:
  //   P = banned in EU cosmetics (the entry says so) or marked as dangerous (carbon black), M = flagged ("bad": EU-restricted, declared allergen, SCCS concern),
  //   L = "mid" (to watch), nothing = ok. The WORST ingredient sets the band; the other ingredients only nudge it:
  //   any P -> 24. Else any M in the first EARLY positions of the list -> 52. Else M further down -> 64, minus 2 for each extra M.
  //   No M and no P -> 100. Then minus 15 x (share of the list that is L). Needs at least 3 rated ingredients.
  // Labels list ingredients from the largest amount to the smallest, so an M near the top counts far more than one at the end.
  // Fitted to OnSkin's published scores on 32 products (leave-one-out error 1.4 points); see docs/calificacion-y-fuentes.md.
  var EARLY = 14, BASE_P = 24, BASE_EARLY = 52, BASE_LATE = 64, PER_EXTRA_M = 2, LOW_WEIGHT = 18;
  // Everyday additives that regulators track but that are not a concern by themselves (preservatives, chelators, pH adjusters,
  // colorants and mineral pigments, ethoxylated emulsifiers, quats, glycols). The app still shows them as "ok"; for the score
  // they count like the "to watch" group, but lightly (see LOW_WEIGHT).
  var LOW_RX = /^((sodium|potassium) (benzoate|sorbate)|benzoic acid|sorbic acid|[a-z ]*edta|ethylhexylglycerin|chlorphenesin|caprylhydroxamic acid|citric acid|acetic acid|lactic acid|(sodium|potassium) hydroxide|tocopheryl acetate|titanium dioxide|zinc oxide|tin oxide|iron oxides?|ultramarines|alumina|silica|lecithin|hydrogenated lecithin|sodium polyacrylate|propanediol|propylene glycol|dipropylene glycol|pentylene glycol|avobenzone|octisalate|ethylhexyl salicylate|butyl methoxydibenzoylmethane|(peg|ppg)[-\/ ]?\d.*|[a-z0-9-]+eth-\d+|polysorbate \d+|poloxamer \d+|polyquaternium-\d+|quaternium-(33|95)|[a-z ]*trimonium (chloride|methosulfate)|ci \d{5}.*|(red|yellow|blue|violet|green|orange) ?\d+( lake)?|phloxine b|sunset yellow.*|brilliant blue.*|lithol rubine.*)$/;
  function analyze(text) {
    var items = split(text || "").map(function (raw) {
      var hit = lookup(raw);
      var name = raw.replace(/\*/g, "").trim(), inci = esName(raw) || name;
      return hit
        ? { name: name, inci: inci, level: hit.level, family: hit.family || null, danger: !!hit.danger, note: hit.note, detail: hit.detail, risks: hit.risks, helps: hit.helps, src: hit.src }
        : { name: name, inci: inci, level: null, family: null, danger: false, note: "", detail: "", risks: [], helps: [], src: [] };
    });
    var n = { good: 0, mid: 0, bad: 0, none: 0 };
    var danger = 0, flagged = [], low = 0;
    items.forEach(function (i, idx) {
      n[i.level || "none"]++;
      if (i.danger) danger++;
      else if (i.level === "bad") flagged.push(idx);
      else if (i.level === "mid" || (i.level !== "bad" && LOW_RX.test((esName(i.name) || i.name).toLowerCase().replace(/\([^)]*\)/g, "").replace(/\s+/g, " ").trim()))) low++;
    });
    var rated = n.good + n.mid + n.bad;
    var score = null;
    if (rated >= 3) {
      var nudge = LOW_WEIGHT * low / items.length;
      if (danger) score = BASE_P;
      else if (!flagged.length) score = 100 - nudge;
      else if (flagged[0] < EARLY) score = BASE_EARLY - nudge;
      else score = BASE_LATE - PER_EXTRA_M * (flagged.length - 1) - nudge;
      score = Math.max(0, Math.min(100, Math.round(score)));
    }
    return { items: items, counts: n, score: score };
  }

    // Animal-derived ingredients, matched by name. Names that say synthetic, vegan or plant milks are skipped.
  // This is a flag-spotting aid, not a certification: glycerin, stearic acid and similar can come from animals or plants.
  var ANIMAL = /(beeswax|cera alba|cera flava|(^|[^a-z])honey|(^|[^a-z])mel([^a-z]|$)|propolis|royal jelly|(^|[^a-z])apis|lanolin|adeps lanae|(^|[^a-z])wool|collagen|elastin|keratin|(^|[^a-z])silk|sericin|(^|[^a-z])milk|(^|[^a-z])lac([^a-z]|$)|lactis|whey|casein|lactoferrin|lactalbumin|(^|[^a-z])egg([^a-z]|$)|ovum|albumen|ovalbumin|lysozyme|gelatin|carmine|ci 75470|cochineal|carminic|snail|secretion filtrate|placenta|tallow|guanine|ci 75170|(^|[^a-z])pearl|nacre|conchiolin|caviar|(^|[^a-z])fish|salmon|oyster|mussel|(^|[^a-z])crab|shrimp|chitosan|swiftlet|bird.?s nest|(^|[^a-z])deer|antler|bee pollen|sodium dna|(^|[^a-z])pdrn|proteoglycan|glycosaminoglycan|cholesterol|castoreum)/;
  var NOT_ANIMAL = /(synthetic|vegan|recombinant|plant|coconut|cocos|soy|glycine soja|oat|avena|almond|amygdal|rice|oryza|eggplant|solanum melongena|milk thistle|silybum|pearl millet|beeswax substitute)/;
  function veganCheck(items) {
    var animal = [];
    (items || []).forEach(function (i) {
      var n = String(i.inci || i.name || "").toLowerCase();
      if (ANIMAL.test(n) && !NOT_ANIMAL.test(n)) animal.push(i.name);
    });
    return { ok: animal.length === 0 && (items || []).length >= 5, animal: animal };
  }

window.Ingredients = { analyze: analyze, split: split, veganCheck: veganCheck, RISK_LABEL: RISK_LABEL, RISK_ICON: RISK_ICON };
})();
